### ISSUE TITLE
url()s with hashes seem to be parsed incorrectly

### ISSUE THREAD

**Issue by mgwalker** [webpack-contrib/css-loader#1039]
- Operating System: macOS 10.14.6
- Node Version: 12.13.1
- NPM Version: 6.13.4
- webpack Version: 4.41.5
- css-loader Version: 3.4.1

### Expected Behavior

This input:
```css
@font-face {
  font-family: Font;
  src: url(url-number-one.ttf);
  src: url(url-number-one.ttf?#two);
}
```

becomes this output:
```css
@font-face {
  font-family: Font;
  src: url(static/fonts/url-number-one.ttf);
  src: url(static/fonts/url-number-one.ttf?#two);
}
```

### Actual Behavior

Get this output:
```css
@font-face {
  font-family: Font;
  src: url(static/fonts/url-number-one.ttf);
  src: url(undefined?#two);
}
```

### Code

[webpack.config.js](https://github.com/mgwalker/css-loader-issue/blob/master/webpack.config.js)

### How Do We Reproduce?

Repro repo here: https://github.com/mgwalker/css-loader-issue

Clone, run `npm install`, then run `npm run build`
