### ISSUE TITLE
Handle :export & :local selectors in non-css-modules mode

### ISSUE THREAD

**Issue by faiwer** [webpack-contrib/css-loader#1087]
Hey all. We faced a specific issue. We started using `css-modules` in a project where are already lots of regular `scss`-files. We gradually move them to `css-modules` way. But it's a long way. 

We have several common files with `scss mixins`. Some of them are about using common (for the app) animations. We do not place animations themselves into our `mixins.scss`, because in such a case they will be copied plenty of times with each `@import`. So our common animations names are __global__.

Imagine these files:
```scss
// animation.scss
@keyframes A {}

// mixins.scss
@mixin M() {
  animation-name: A;
}

// css-module.mod.scss
@import '.../mixins.scss';
.S { @include M; }

// regular-css.scss
@import '.../mixins.scss';
.S { @include M; }
```
Files end with `.mod.scss` use `module: true` (in `css-loader`). Regular files use `module: false`.
And ... It doesn't work well.

Loader that uses css-modules mangles `A` into `A_randomhash`. Animation is broken. 
I can fix it with:
```scss
@mixin M() {
  :global { animation-name: A; }
}
```
Now in css-modules files it works. But it's broken in non-css-modules files.
Okay, what's about next:
```scss
@mixin M() {
  animation-name: A; 
  &:global { animation-name: A; }
}
```
Now it works everywhere. Wow. Oh, no. There's extra trash-css in non-css-modules output:
```scss
.S {...}
.S:export {...}
```

I'm curious how to handle it properly. I can write additional one loader, that would remove all excess selectors in non-css-modules files during transpiling process. But it looks like the proper solution would be: autoremove selectors with `:global` inside of them when `modules: false`. 

Or no? I don't know.
