### ISSUE TITLE
Multi entrypoint styles duplication with preprocessors like stylus

### ISSUE THREAD

**Issue by midnightcoder-pro** [webpack-contrib/css-loader#1207]
- Operating System: Windows 10 2004
- Node Version: 14.11.0
- NPM Version: 6.14.8
- webpack Version: 4.44.2
- css-loader Version: 4.3.0
- stylus-loader Version: 4.1.1

### Expected Behavior

```css
.box,.child,.test{border-width:2px;border-style:solid;padding:0 20px;margin:0 6px;max-width:400px}
.child{border-style:dotted;border-color:#008000}
.test{border-color:#f00}
```

### Actual Behavior

```css
.box{border-width:2px;border-style:solid;padding:0 20px;margin:0 6px;max-width:400px}
.box,.child{border-width:2px;border-style:solid;padding:0 20px;margin:0 6px;max-width:400px}
.child{border-style:dotted;border-color:#008000}
.box,.test{border-width:2px;border-style:solid;padding:0 20px;margin:0 6px;max-width:400px}
.test{border-color:#f00}
```

### How Do We Reproduce?
[Repo](https://github.com/midnightcoder-pro/stylus-duplication-demo)
```
yarn build
```

**Comment by midnightcoder-pro** [comment]
Or is it a bug in extract-css-chunks-webpack-plugin?

**Comment by evilebottnawi** [comment]
Yes, it is bug on extract-css-chunks-webpack-plugin side, I recommend to use `mini-css-extract-plugin`

**Comment by midnightcoder-pro** [comment]
I get the same output from mini-css-extract-plugin

**Comment by evilebottnawi** [comment]
Okay, I will look at this in near future, but mostly it is configuration problems, or you duplicate modules

**Comment by evilebottnawi** [comment]
My actual result is:
```css
.box{border-width:2px;border-style:solid;padding:0 20px;margin:0 6px;max-width:400px}
.box,.child{border-width:2px;border-style:solid;padding:0 20px;margin:0 6px;max-width:400px}.child{border-style:dotted;border-color:#008000}
.box,.test{border-width:2px;border-style:solid;padding:0 20px;margin:0 6px;max-width:400px}.test{border-color:#f00}
```

No problems, look at `dist` directory

**Comment by midnightcoder-pro** [comment]
I expected to see this result: [single entry](https://github.com/midnightcoder-pro/stylus-duplication-demo/tree/single-entry/dist/bundle.css)

**Comment by evilebottnawi** [comment]
@midnightcoder-pro you need to setup minificator https://github.com/webpack-contrib/css-minimizer-webpack-plugin, CSS minification is out of scope `css-loader`

**Comment by midnightcoder-pro** [comment]
In my opinion, this is a loss of context, not a minimization task. Stylus doesn't know anything about entry points and processes them separately.
`css-minimizer-webpack-plugin` [gives](https://github.com/midnightcoder-pro/stylus-duplication-demo/blob/with-minimizer/dist/bundle.css) an incorrect result in comparison with [single entry point](https://github.com/midnightcoder-pro/stylus-duplication-demo/tree/single-entry/dist/bundle.css) setup

**Comment by evilebottnawi** [comment]
@midnightcoder-pro https://github.com/webpack-contrib/css-loader/issues/1207#issuecomment-707798853 it is what `stylus-loader` returns to css-loader, we don't touch your CSS

**Comment by midnightcoder-pro** [comment]
But this part is handled by `css-loader`?
```js
import './parent.styl'
import './child.styl'
import './test.styl'
```
Aren't these three separate launches of the `stylus-loader`?

**Comment by evilebottnawi** [comment]
What is the problem? We handle CSS returned from `style-loader`, we don't merge CSS, we don't change it, we just handle `url`/`@import`

**Comment by midnightcoder-pro** [comment]
> ### Expected Behavior
> ```css
> .box,.child,.test{border-width:2px;border-style:solid;padding:0 20px;margin:0 6px;max-width:400px}
> .child{border-style:dotted;border-color:#008000}
> .test{border-color:#f00}
> ```
> 
> ### Actual Behavior
> ```css
> .box{border-width:2px;border-style:solid;padding:0 20px;margin:0 6px;max-width:400px}
> .box,.child{border-width:2px;border-style:solid;padding:0 20px;margin:0 6px;max-width:400px}
> .child{border-style:dotted;border-color:#008000}
> .box,.test{border-width:2px;border-style:solid;padding:0 20px;margin:0 6px;max-width:400px}
> .test{border-color:#f00}
> ```
Is it stylus-loader or style-loader problem?

**Comment by evilebottnawi** [comment]
This is a problem neither `style-loader` or `style-loader`, this result:
```css
.box{border-width:2px;border-style:solid;padding:0 20px;margin:0 6px;max-width:400px}
.box,.child{border-width:2px;border-style:solid;padding:0 20px;margin:0 6px;max-width:400px}.child{border-style:dotted;border-color:#008000}
.box,.test{border-width:2px;border-style:solid;padding:0 20px;margin:0 6px;max-width:400px}.test{border-color:#f00}
```

was returned from `stylus`, so you need to `stylus` about this
