### ISSUE TITLE
Loader removes quotes around path in url()

### ISSUE THREAD

**Issue by i-gavriliuk** [webpack-contrib/css-loader#1237]
- Operating System: Debian 10 (buster)
- Node Version: v14.15.1
- NPM Version: 6.14.8
- webpack Version: 5.9.0
- css-loader Version: 5.0.1
- mini-css-extract-plugin Version: 1.3.1

### Expected Behavior

css-loader resolves urls, but does not change the formatting of the source code

### Actual Behavior

css-loader resolves urls and removes quotes around paths

### Code

**Source code:**
```css
@font-face {
  font-family: "Georgia";
  src: url("./assets/fonts/Georgia-Regular.woff2") format("woff2"),   /* double quotes in url() */
       url('./assets/fonts/Georgia-Regular.woff') format("woff");     /* single quotes in url() */
}
.first-div {
  background-image: url("./assets/images/puppy.jpg");                 /* double quotes in url() */
}
.second-div {
  background-image: url('./assets/images/puppy.jpg');                 /* single quotes in url() */
}
.third-div {
  background-image: url(./assets/images/puppy.jpg);                   /* path in url() without quotes */
}
```

**Result code:**
```css
/* all paths in url() without quotes */
@font-face {
  font-family: "Georgia";
  src: url(../fonts/Georgia-Regular.woff2) format("woff2"),
       url(../fonts/Georgia-Regular.woff) format("woff");
}
.first-div {
  background-image: url(../images/puppy.jpg);
}
.second-div {
  background-image: url(../images/puppy.jpg);
}
.third-div {
  background-image: url(../images/puppy.jpg);
}
```

### How Do We Reproduce?

Repro repo here: https://github.com/i-gavriliuk/css-loader-bug

**Comment by alexander-akait** [comment]
Expected, we insert quotes if it is necessary, it is not break code

**Comment by i-gavriliuk** [comment]
> Expected, we insert quotes if it is necessary, it is not break code

This is not a significant enough argument for `url()` to have exactly this format. The absence of whitespace characters don't break code too, but you leave them in the code.
The whole teams develop style guides, authors write the code in accordance with them, and you say that "**It doesn't matter what the code looks like, it works**". It is strange, that the code of css-loader has the unified figuration.

From the documentation of css-loader:
> The css-loader interprets `@import` and `url()` like `import/require()` and will resolve them.

There's nothing said that it also modifies `url()` into the format that is the only correct according to your opinion.

From CSS specification:
> For legacy reasons, a `url()` can be written without quotation marks around the URL itself, in which case it is specially-parsed as a url-token.

So you consider legacy format of record to be ok for modern tool.

I think, that if someone needs to optimize or minimize the CSS code, he is able to decide himself and use more powerful than CSS-loader tools that are specially designed for optimization in Webpack.

**Comment by alexander-akait** [comment]
We can't keep quotes, because final filename of files can be any, for example if you have code:
```css
div {
  background: url(./images/static.png);
}
```

and use `file-loader` with `name: '[name]-'-.[ext]'`(any other illegal characters) we need to quote your URL, otherwise code will be broken. 

> The whole teams develop style guides, authors write the code in accordance with them, and you say that "It doesn't matter what the code looks like, it works". It is strange, that the code of css-loader has the unified figuration.

> There's nothing said that it also modifies url() into the format that is the only correct according to your opinion.

It is bundled code, it is always look ugly, because it is for machines, not for developers.

> So you consider legacy format of record to be ok for modern tool.

It does not say that this is an legacy format, it says that it works for backward compatibility

> I think, that if someone needs to optimize or minimize the CSS code, he is able to decide himself and use more powerful than CSS-loader tools that are specially designed for optimization in Webpack.

As I said before final filenames will be known only after complete bundling, keeping them in original format increase runtime and decrease perf, between perf and keeping quotes bundler choose perf
