### ISSUE TITLE
Versio 5.2.0 can't handle image/svg+xml based valid CSS syntax anymore

### ISSUE THREAD

**Issue by j0sk** [webpack-contrib/css-loader#1284]
- Operating System: OSX
- Node Version: 14.15.1 (stable)
- NPM Version: 6.14.8
- webpack Version: 5.28.0
- css-loader Version: 5.2.0

### Expected Behavior

CSS-LOADER should handle following W3C CSS3 validated CSS syntax for SVG data images.

Following CSS code can be found here: [https://jsfiddle.net/gwudzpaj/](https://jsfiddle.net/gwudzpaj/)

I have validated the css syntax so there is no issues at all.

.broken-first {background-image:url(data:image/svg+xml,%3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22UTF-8%22%3F%3E%3Csvg%20width%3D%2232%22%20height%3D%2232%22%20viewBox%3D%220%200%2032%2032%22%20version%3D%221.1%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Cdefs%3E%3CradialGradient%20id%3D%22dot%22%3E%3Cstop%20stop-color%3D%22%23EE5A00%22%20%2F%3E%3Cstop%20offset%3D%2247.5%%22%20stop-color%3D%22%23EE5A00%22%20%2F%3E%3Cstop%20offset%3D%2252.5%%22%20stop-color%3D%22%23FFFFFF%22%20stop-opacity%3D%220%22%20%2F%3E%3C%2FradialGradient%3E%3C%2Fdefs%3E%3Ccircle%20cx%3D%2216%22%20cy%3D%2216%22%20r%3D%2216%22%20fill%3D%22url%28%23dot%29%22%20%2F%3E%3C%2Fsvg%3E);background-position:50%;background-repeat:no-repeat;background-size:cover;background-origin:border-box}
.broken-second {background-image:url(data:image/svg+xml,%3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22UTF-8%22%3F%3E%3Csvg%20width%3D%2232%22%20height%3D%2232%22%20viewBox%3D%220%200%2032%2032%22%20version%3D%221.1%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Cdefs%3E%3CradialGradient%20id%3D%22dot%22%3E%3Cstop%20stop-color%3D%22%23BEBEBE%22%20%2F%3E%3Cstop%20offset%3D%2247.5%%22%20stop-color%3D%22%23BEBEBE%22%20%2F%3E%3Cstop%20offset%3D%2252.5%%22%20stop-color%3D%22%23FFFFFF%22%20stop-opacity%3D%220%22%20%2F%3E%3C%2FradialGradient%3E%3C%2Fdefs%3E%3Ccircle%20cx%3D%2216%22%20cy%3D%2216%22%20r%3D%2216%22%20fill%3D%22url%28%23dot%29%22%20%2F%3E%3C%2Fsvg%3E)}

### Actual Behavior

`
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
  URIError: URI malformed
`

### How Do We Reproduce?

Just add following validated CSS and version 5.2.0 can't handle that. It works just fine using the version 5.1.4.

Following CSS code can be found here: [https://jsfiddle.net/gwudzpaj/](https://jsfiddle.net/gwudzpaj/)

.broken-first {background-image:url(data:image/svg+xml,%3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22UTF-8%22%3F%3E%3Csvg%20width%3D%2232%22%20height%3D%2232%22%20viewBox%3D%220%200%2032%2032%22%20version%3D%221.1%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Cdefs%3E%3CradialGradient%20id%3D%22dot%22%3E%3Cstop%20stop-color%3D%22%23EE5A00%22%20%2F%3E%3Cstop%20offset%3D%2247.5%%22%20stop-color%3D%22%23EE5A00%22%20%2F%3E%3Cstop%20offset%3D%2252.5%%22%20stop-color%3D%22%23FFFFFF%22%20stop-opacity%3D%220%22%20%2F%3E%3C%2FradialGradient%3E%3C%2Fdefs%3E%3Ccircle%20cx%3D%2216%22%20cy%3D%2216%22%20r%3D%2216%22%20fill%3D%22url%28%23dot%29%22%20%2F%3E%3C%2Fsvg%3E);background-position:50%;background-repeat:no-repeat;background-size:cover;background-origin:border-box}
.broken-second {background-image:url(data:image/svg+xml,%3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22UTF-8%22%3F%3E%3Csvg%20width%3D%2232%22%20height%3D%2232%22%20viewBox%3D%220%200%2032%2032%22%20version%3D%221.1%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Cdefs%3E%3CradialGradient%20id%3D%22dot%22%3E%3Cstop%20stop-color%3D%22%23BEBEBE%22%20%2F%3E%3Cstop%20offset%3D%2247.5%%22%20stop-color%3D%22%23BEBEBE%22%20%2F%3E%3Cstop%20offset%3D%2252.5%%22%20stop-color%3D%22%23FFFFFF%22%20stop-opacity%3D%220%22%20%2F%3E%3C%2FradialGradient%3E%3C%2Fdefs%3E%3Ccircle%20cx%3D%2216%22%20cy%3D%2216%22%20r%3D%2216%22%20fill%3D%22url%28%23dot%29%22%20%2F%3E%3C%2Fsvg%3E)}

**Comment by alexander-akait** [comment]
You have broken URL, you need ignore them:

```css
.broken-first {
/** webpackIngore: true **/
  background-image:url(data:image/svg+xml,%3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22UTF-8%22%3F%3E%3Csvg%20width%3D%2232%22%20height%3D%2232%22%20viewBox%3D%220%200%2032%2032%22%20version%3D%221.1%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Cdefs%3E%3CradialGradient%20id%3D%22dot%22%3E%3Cstop%20stop-color%3D%22%23EE5A00%22%20%2F%3E%3Cstop%20offset%3D%2247.5%%22%20stop-color%3D%22%23EE5A00%22%20%2F%3E%3Cstop%20offset%3D%2252.5%%22%20stop-color%3D%22%23FFFFFF%22%20stop-opacity%3D%220%22%20%2F%3E%3C%2FradialGradient%3E%3C%2Fdefs%3E%3Ccircle%20cx%3D%2216%22%20cy%3D%2216%22%20r%3D%2216%22%20fill%3D%22url%28%23dot%29%22%20%2F%3E%3C%2Fsvg%3E);background-position:50%;background-repeat:no-repeat;background-size:cover;background-origin:border-box
}

.broken-second {
/** webpackIngore: true **/
  background-image:url(data:image/svg+xml,%3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22UTF-8%22%3F%3E%3Csvg%20width%3D%2232%22%20height%3D%2232%22%20viewBox%3D%220%200%2032%2032%22%20version%3D%221.1%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Cdefs%3E%3CradialGradient%20id%3D%22dot%22%3E%3Cstop%20stop-color%3D%22%23BEBEBE%22%20%2F%3E%3Cstop%20offset%3D%2247.5%%22%20stop-color%3D%22%23BEBEBE%22%20%2F%3E%3Cstop%20offset%3D%2252.5%%22%20stop-color%3D%22%23FFFFFF%22%20stop-opacity%3D%220%22%20%2F%3E%3C%2FradialGradient%3E%3C%2Fdefs%3E%3Ccircle%20cx%3D%2216%22%20cy%3D%2216%22%20r%3D%2216%22%20fill%3D%22url%28%23dot%29%22%20%2F%3E%3C%2Fsvg%3E)
}
```
