### ISSUE TITLE
Font loading stopped working in 6.0.0

### ISSUE THREAD

**Issue by mtmacdonald** [webpack-contrib/css-loader#1354]
**Summary: since `css-loader` 6.0.0, my app no longer imports and displays web fonts correctly.**

- Operating System: `Mac OS Big Sur version 11.3.1`
- Node Version: `14.15.0`
- NPM Version: `6.14.8`
- webpack Version: `5.47.0`
- css-loader Version: `6.0.0` up to `6.2.0`

### Expected Behavior

Imported fonts load and display correctly.

### Actual Behavior

Imported fonts don't display, and browsers give me these errors. In Chrome:

<img width="1388" alt="Screenshot 2021-07-28 at 10 59 33" src="https://user-images.githubusercontent.com/2428859/127303711-ca0cf236-0892-469d-aca4-7503d408e96c.png">

and Firefox:

<img width="999" alt="Screenshot 2021-07-28 at 10 51 28" src="https://user-images.githubusercontent.com/2428859/127302448-65d4152e-73fa-4fd6-8294-e7dee093a940.png">

### Code

My app is an open-source repository: [react-ui-library](https://gitlab.com/oliasoft-open-source/react-ui-library). The master branch is still using css-loader `5x` (just bump it to `6x` to reproduce). 

I will give a summary of the code parts I think are relevant here.

`src/style/fonts.less`:

```js
@font-face {
  font-family: 'Lato';
  font-weight: normal;
  font-style: normal;
  src: url('./fonts/lato/Lato-Regular.woff2') format('woff2');
}
```

`webpack/webpack.common.rules.less`:

```js
    {
      test: /\.(ttf|eot|woff|woff2)$/,
      use: [
        {
          loader: 'file-loader',
          options: {
            name: './fonts/[name].[contenthash].[ext]',
          },
        },
      ],
    },

    {
      test: /^(?!.*?(\.module)).*\.less$/, //all *.less except for *.module.less
      use: [
        styleLoader,
        {
          loader: 'css-loader',
          options: {
            sourceMap: env === 'development',
          },
        },
        'less-loader',
      ],
    },
```

### How Do We Reproduce?

Check out the  [repository](https://gitlab.com/oliasoft-open-source/react-ui-library) master branch. Bump the `css-loader` version `6x`. Then `npm install` and `npm run dev:docs` to run the app. The errors can be seen in the console.

**Comment by tedw** [comment]
@mtmacdonald Glad it’s not just me! I’ve run into this on two separate projects after upgrading to v6.

One is a WordPress site built on top of the [Sage](https://roots.io/sage/) theme framework (v9, using Webpack). Here’s their default Webpack config: https://github.com/roots/sage/blob/a3055a4469727c2becaacbb8612f9f49d9a670ee/resources/assets/build/webpack.config.js#L62-L120

The other site is built with Eleventy, using this boilerplate’s Webpack config:
https://github.com/clenemt/eleventy-webpack/blob/master/webpack.config.js

After upgrading to v6, any fonts referenced via `@font-face` in my CSS are renamed using just a hash and are copied to the root directory.

Before:
```css
@font-face {
  font-family: "Zilla Slab";
  font-style: normal;
  font-weight: 400;
  src: url("../fonts/zilla-slab/zilla-slab-regular.woff2") format("woff2"),
       url("../fonts/zilla-slab/zilla-slab-regular.woff") format("woff");
}
```

After
```css
@font-face {
  font-family: "Zilla Slab";
  font-style: normal;
  font-weight: 400;
  src: url(/assets/11cf47d98920cdfba843.woff2) format("woff2"),
       url(/assets/8b7198a7b0b7f94ddc05.woff) format("woff"); }
```

Interestingly, I tried adding `type: 'asset/resource',` to my config (https://webpack.js.org/guides/asset-management/#loading-fonts) but that actually caused the same issue in **v5**. I don’t know enough about how `css-loader` and Webpack work to know what this means but I hope it helps someone else figure out what’s going on!
