### ISSUE TITLE
Buggy example for Resolve unresolved URLs using an alias (missing tilde char)

### ISSUE THREAD

**Issue by coderars** [webpack-contrib/css-loader#1398]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [x] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

The instructions for [Resolve unresolved URLs using an alias](https://github.com/webpack-contrib/css-loader#resolve-unresolved-urls-using-an-alias) presents this example CSS:
```css
.class {
  background: url(/assets/unresolved/img.png);
}
```
However this will still lead to `Module not found: Error: Can't resolve ...`, even if `resolve.alias` is set properly. I've just run into it and took me some time, before I noticed one other part of the [documentation](https://github.com/webpack-contrib/css-loader#url) for `url`, which says that **for alias, prefix it with a `~`** :
> To import assets from a node_modules path (include resolve.modules) and for alias, prefix it with a ~

So after putting that tilde before the aliased `url` in my CSS it worked as expected.

webpack 5.64.4
css-loader 6.5.1

### Your Proposal for Changes
```css
.class {
  background: url(~/assets/unresolved/img.png);
}
```
