### ISSUE TITLE
Duplicate CSS into the development bundle

### ISSUE THREAD

**Issue by xavierfoucrier** [webpack-contrib/css-loader#1433]
Hi webpack team!

Hope it's an interesting case :pray: 

Two entry points in my application:
```js
  entry: [
    'scripts/index.js',
    'styles/build.scss',
  ],
```

I am using a CSS framework, so I am importing it using a regular `@use` rule into my `build.scss` file to be able to use global variables/components at the style (SCSS) level. In addition, I am importing the same library into my `index.js` at the script (JS) level to access some variables, like breakpoints/settings, for more flexibility.

The thing is, now when bundling the application, my `app.css` contains two times the library in the bundled file.

```css
/*!*****************************************************************************************************************************************************************************************************************************************************!*\
  !*** css ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[0].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[0].use[2]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[0].use[3]!./src/assets/styles/build.scss ***!
  \*****************************************************************************************************************************************************************************************************************************************************/
.library {
  color: #737373;
}

/*!*****************************************************************************************************************************************************************************************************************************************************!*\
  !*** css ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[0].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[0].use[2]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[0].use[3]!./src/assets/styles/library.scss ***!
  \******************************************************************************************************************************************************************************************************************************************************/
.library {
  color: #737373;
}

/*# sourceMappingURL=app.css.map*/
```

When commenting the SCSS or JS import, it works fine and import the library once, but I need to import in both of course.
I don't understand why it's importing two times the same CSS...

Let me know if it's related to another webpack plugin, or if it's the default behavior.

Thanks a lot! :wink: 

> Note that it works fine for production, as the bundle is tree-shaked and minified.

```bash
  Packages:
    babel-loader: ^8.2.4 => 8.2.4
    copy-webpack-plugin: ^10.2.4 => 10.2.4
    css-loader: ^6.7.1 => 6.7.1
    css-minimizer-webpack-plugin: ^3.4.1 => 3.4.1
    eslint-webpack-plugin: ^3.1.1 => 3.1.1
    handlebars-webpack-plugin: ^2.2.1 => 2.2.1
    postcss-loader: ^6.2.1 => 6.2.1
    purgecss-webpack-plugin: ^4.1.3 => 4.1.3
    sass-loader: ^12.6.0 => 12.6.0
    stylelint-webpack-plugin: ^3.2.0 => 3.2.0
    svg-spritemap-webpack-plugin: ^4.4.0 => 4.4.0
    terser-webpack-plugin: ^5.3.1 => 5.3.1
    webpack: ^5.70.0 => 5.70.0
    webpack-bundle-analyzer: ^4.5.0 => 4.5.0
    webpack-cli: ^4.9.2 => 4.9.2
    webpack-dev-server: ^4.7.4 => 4.7.4
    webpack-merge: ^5.8.0 => 5.8.0
```
