### ISSUE TITLE
Detect @font-face urls()

### ISSUE THREAD

**Issue by jhnns** [webpack-contrib/css-loader#2]
It seems like the css-loader doesn't detect url()s in @font-face declarations

``` css
@font-face {
    font-family: 'Museo300';
    src: url(../assets/fonts/Museo/museo300-regular.woff) format('woff'),
         url(../assets/fonts/Museo/museo300-regular.ttf) format('truetype'),
         url(../assets/fonts/Museo/museo300-regular.svg) format('svg');
    font-weight: normal;
    font-style: normal;
}
```

This declaration is pretty standard (actually generated by [fontsquirrel](http://www.fontsquirrel.com/)) to support different font formats.
