### ISSUE TITLE
the publicPath  dosen't resolve the css background url path, just use ''+'' concat the string

### ISSUE THREAD

**Issue by monkindey** [webpack-contrib/css-loader#209]
my src is  

``` javascript
├── src
|   ├── css
|   |    └──  index.less
|   ├── img
|   |    └── bg.png
|   └── js
|        └── main.js
.

```

but i want to  compile to dist folder as the same structure like

``` javascript

├── dist
|   ├── css
|   |    └── index.css
|   ├── assets
|   |    └── bg.png
|   └── js
|        └── bundle.js
├── src
.   └── ..
```

my `webpack.config.js` is like that 

``` javascript
'use strict'

var DEV_JS_PATH = __dirname + '/www/static/js/';
// var HtmlWebpackPlugin = require('html-webpack-plugin');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var path = require('path');

module.exports = {
    entry: {
        index: DEV_JS_PATH + 'index.jsx',
        history: DEV_JS_PATH + 'history.jsx'
    },
    output: {
        path: __dirname + '/www/dist/js',
        filename: '[name].js'
    },
    resolve: {
        extensions: ["", ".js", ".jsx"],

    },
    module: {
        loaders: [{
            test: /\.less$/,
            loader: ExtractTextPlugin.extract('style', 'css!less', {
                publicPath: '/dist/css/'
            })
        }, {
            test: /(\.png|\.jpg)$/,
            loader: 'url?limit=8000&name=../img/[name].[ext]'
        }, {
            test: /\.jsx$/,
            loader: 'babel-loader'
        }, {
            test: /\.(eot|ttf|svg|woff(2)?)/,
            loader: 'file-loader'
        }]
    },
    plugins: [  
        new ExtractTextPlugin('../css/[name].css'),
    ]
}
```

and my less the background img url is 

``` css
.content {
    height: 80%;
    background: url(../img/bg.png) no-repeat;
    background-size: cover;
    text-align: center;
}
```

 my expectations is 

``` css
.content {
    height: 80%;
    background: url(dist/img/bg.png) no-repeat;
    background-size: cover;
    text-align: center;
}
```

but it is like that

``` css
.content {
    height: 80%;
    background: url(dist/css/../img/bg.png) no-repeat;
    background-size: cover;
    text-align: center;
}
```

i watch the  source , i see that 

``` javascript
/* 22 */
/***/ function(module, exports, __webpack_require__) {

    module.exports = __webpack_require__.p + "../img/bg.png";

/***/ },
/* 23 */
```
