### ISSUE TITLE
Clarify importLoaders documentation?

### ISSUE THREAD

**Issue by BerndWessels** [webpack-contrib/css-loader#228]
I tried to understand `importLoaders` from the readme but completely don't get it.

Can anybody please give a better explanation of what `importLoaders` do?

Thank you
Bernd

**Comment by mummybot** [comment]
I'm new to Webpack as well and as I understand it, It does what is says on the [tin](https://github.com/webpack/css-loader#importing-and-chained-loaders): 

> importLoaders allow to configure which loaders should be applied to @imported resources.

Given the following CSS:
```CSS
/* File style.css */
@import "body.css";
body {
    /*background: yellow;*/
    font-size: 20px;
}
div {
    display: flex;
}
/* File body.css */
$color: red;
body {
	background: $color;
}
div {
	color: white;
	a {
		color: green;
	}
}
div {
	display: flex;
}
```
On a basic set up with using PostCSS the following would only apply PostCSS plugins to style.css, NOT the @imported body.css:
```javascript 
module: {
    loaders: [
        {
            test:   /\.css$/,
            loader: "style-loader!css-loader!postcss-loader"
        }
    ]
},
postcss: function() {
    return [autoprefixer, precss];
}
```
To get autoprefixer (and precss) working on @imported CSS files we use importLoaders instead:
```javascript
module: {
    loaders: [
        {
            test:   /\.css$/,
            loader: 'style!css?importLoaders=1!postcss'
        }
    ]
},
postcss: function() {
    return [autoprefixer, precss];
}
```
I assume this has something to do with how Webpack loaders parse assets. You have to explicitly tell the loader to interpret @import directives. Why that isn't done by default or as an option in style-loader or css-loader I don't know - maybe there is a way of doing it that I am missing.
