### ISSUE TITLE
Possible to hoist "compose" classes in the css output?

### ISSUE THREAD

**Issue by snaptopixel** [webpack-contrib/css-loader#230]
I ran into a specificity issue today using `compose` that was not fun. My require/import structure was originally like this and everything worked fine:

```
Input order:
index.css -> component.css -> shared.css 
Output order:
shared.css -> component.css -> index.css (bottom of css file)
```

Then I needed to `compose` a class inside index.css which broke css that had been working:

```
New input order:
index.css -> shared.css -> component.css -> shared.css
New output order:
component.css -> shared.css -> index.css
```

Here's some pseudo-code that shows the problem. It worked fine (the text was green) until shared.css was used in index.css, then the blue text took precedence.

``` css
/* shared.css */
.foo {
color:blue;
}
/* component.css */
.bar {
composes: foo from "shared.css";
color: green;
}
```

It seems like the solution would be to hoist any composed classes above non composed classes in the final output. This obviously has complexities when multiple composition comes into play, but I wanted to document the issue and see if anyone had ideas or thoughts that may help.
