### ISSUE TITLE
@font-face wrong syntax

### ISSUE THREAD

**Issue by renanvalentin** [webpack-contrib/css-loader#233]
Hey guys,

I'm stuck on this problem all day long and I can't find a way to solve this, could you help me please?
If minimized is enabled, than the @font-face is stripped out, but if I disable it, the final file comes with a wrong syntax, like this:

``` css
@font-face {
{
  font-family: 'whatsgood-fonticon'
;
  src: url(../fonts/whatsgood-fonticon.eot)
;
  src: url(../fonts/whatsgood-fonticon.eot#iefix) format("embedded-opentype"), url(../fonts/whatsgood-fonticon.ttf) format("truetype"), url(../fonts/whatsgood-fonticon.woff) format("woff"), url(../fonts/whatsgood-fonticon.svg#whatsgood-fonticon) format("svg")
;
  font-weight: normal
;
  font-style: normal
}
}
```

**Comment by renanvalentin** [comment]
Pretty strange, I will take a look later, but this approach works!

```css
@font-face {
  font-family: 'whatsgood-fonticon';
  src: url('./whatsgood-fonticon.eot?pqypst');
  src: url('./whatsgood-fonticon.eot?pqypst#iefix') format('embedded-opentype'),
  url('./whatsgood-fonticon.ttf?pqypst') format('truetype'),
  url('./whatsgood-fonticon.woff?pqypst') format('woff'),
  url('./whatsgood-fonticon.svg?pqypst#whatsgood-fonticon') format('svg');
  font-weight: normal;
  font-style: normal;
}

:global {
  [class^="wg-"], [class*=" wg-"] {
    font-family: 'whatsgood-fonticon' !important;
    speak: none;
    font-style: normal;
    font-weight: normal;
    font-variant: normal;
    text-transform: none;
    line-height: 1;

    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
  }

  .wg-add:before {
    content: "\e900";
  }
  .wg-arrow-down:before {
    content: "\e901";
  }
}
```
