### ISSUE TITLE
export classes (include `:global`)

### ISSUE THREAD

**Issue by DragorWW** [webpack-contrib/css-loader#258]
if not use css-module, how to get class from file ?

``` css
//style.css
.block {width:1 00%;}
.block_mod {color: red;}
```

``` js
//index.es6
import slyle form './style.css';
//style = [
//  'block',
//  'block_mod'
//];
```

**Comment by psimyn** [comment]
not sure that you can if not using css modules. Using modules you can print the key names (NB: this also seems to print IDs as well as styles.)

```
// style.css
.block:local {width:1 00%;}
.block_mod:local {color: red;}
```

```
// index.es6
import style form './style.css';
console.log(Object.keys(style));
// prints:
// [ 'block', 'block_mod' ];
```

If you don't want to use css modules maybe `grep \.[a-z]` ?

**Comment by DragorWW** [comment]
@psimyn in my project server side rendering html and i can't use css module on server.
But i want check class in js by css;

expamle

```css
//style.css
.block {width:100%;}
.block_size_big {color: red;}
```
```js
//index.es6
import slyle form './style.css';

var classList = new ClassList(style);

classList.mod('size','big'); // ok
classList.mod('size','normal'); // error this mod not found in styles

```
