### ISSUE TITLE
Keyframe and Animation Names are Not Applied

### ISSUE THREAD

**Issue by netpoetica** [webpack-contrib/css-loader#264]
css-loader seems to take @keyframes animation names and cacheify them in a way where they are no longer appropriately applied. Per example:

I pulled a [CSS loader](http://cssload.net/en/spinners/7) with code like so

``` css
.cssload-loader {
        animation-name: cssload-loader;
}
@keyframes cssload-loader {
        from { transform: scale(0); opacity: 1; }
        to   { transform: scale(1); opacity: 0; }
}
```

and then in my React component

``` js
import LoaderStyles from 'styles/components/Loader';

//...

render () {
  return (
        <div className={LoaderStyles['wrapper']}>
          <div className={LoaderStyles['cssload-loader']}></div>
        </div>
  );
}
```

But the animation is never applied. The CSS that PostCSS/css-loader generates contains an animation name with cacheable values added, but apparently that animation does not exist?

``` css
.Loader__cssload-loader___2MBLL {
    animation-name: Loader__cssload-loader___2MBLL;
}
```

I cannot find anything in the issues here, on the googles, or on StackOverflow that explains how animations are supposed to be handled by PostCSS & css-loader. Am I missing something?

**Comment by gucheen** [comment]
+1 same trouble


```
:local .a {
  animation: someAnimation
}

@keyframes :local(someAnimation) {

}
```

The animation's name in `.a` has been transformed into hash, but keyframe's name hasn't (still 'someAnimation')

**Comment by netpoetica** [comment]
@gucheen In regards to your update, are you saying this works for you if you don't use :local ?

**Comment by gucheen** [comment]
@netpoetica 
My problem was that I used animation in `:local .a:before { } `.
Finally I move animation property to `:local .a {}`

**Comment by raveclassic** [comment]
@gucheen It's not working even with plain selectors without pseudo classes.
```
:local {
	@keyframes fadeOut {
		0% {
			opacity: 1;
			visibility: visible;
		}
		100% {
			opacity: 0;
			visibility: hidden;
		}
	}

	.test {
		animation: fadeOut 1000ms ease-in;
	}
}
```

output:
```
.src-plugins-test__test {
	animation: src-plugins-test__fadeOut 1000ms ease-in;
}

@keyframes fadeOut {
	0% {
		opacity: 1;
		visibility: visible;
	}
	100% {
		opacity: 0;
		visibility: hidden;
	}
}
```

Guys, do you have any update on this? I believe this is a major bug.

**Comment by QuietOmen** [comment]
Is there a way to specify that pseudo classes shouldn't be hashed? This would help me to use cq-prolyfill which adds the pseudo class ```:container``` and allows you to carry out container queries.

**Comment by isnifer** [comment]
Less working example:
```less
@keyframes ~":local(button-preload)" {
    0% {
        background-position: 0 0;
    }
    100% {
        background-position: 20px 0;
    }
}

:local {
    .button-preload() {
        background-position: 0 0;
        animation: button-preload 750ms linear infinite;
    }

    .button {
        &__preload {
            .button-preload();
            color: #fff;
        }
    }
}
```

**Comment by AlejandroEsquivel** [comment]
This worked for me

```css
@-webkit-keyframes :local(animatetop) {
  from {top:-300px; opacity:0}
  to {top:0; opacity:1}
}
@keyframes :local(animatetop) {
  from {top:-300px; opacity:0}
  to {top:0; opacity:1}
}
:local(.modalContent) :local{
    position: relative;
    background-color: white;
    margin: auto;
    padding: 0;
    border: 1px solid #888;
    width: 500px;
    min-height:300px;
    box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2),0 6px 20px 0 rgba(0,0,0,0.19);
    -webkit-animation-name: animatetop;
    -webkit-animation-duration: 0.4s;
    animation-name: animatetop;
    animation-duration: 0.4s
}
```
