### ISSUE TITLE
Reporting undefined @value and :import

### ISSUE THREAD

**Issue by paulyoung** [webpack-contrib/css-loader#269]
Is there a way to error on `undefined` values?

For example:

``` css
:import('foo.css') {
  foo: foo;
}

@value bar from 'bar.css';

body {
  background-color: foo;
  color: bar;
}
```

produces:

``` css
body {
  background-color: undefined;
  color: undefined;
}
```
