### ISSUE TITLE
Way to disable classname changing

### ISSUE THREAD

**Issue by mmjamal** [webpack-contrib/css-loader#272]
Hello 

I have react component that generates divs with specific classnames - now i when i import the css - the css-loader seem to change the classnames and my generated dom classnames are not valid anymore - is there way to disable changing the classnames to unique ids and leave them as they are

**Comment by psimyn** [comment]
You can wrap them in a :global {}  block, or disable modules in webpack config

**Comment by dwilt** [comment]
I've got some keyframes in a `:global` block and it's still changing those names. For example:

```css
:global {
    @keyframes slideInUp {
        from {
            transform: translate3d(0, 100%, 0);
            visibility: visible;
        }

        to {
            transform: translate3d(0, 0, 0);
        }
    }

    @keyframes slideOutDown {
        from {
            transform: translate3d(0, 0, 0);
        }

        to {
            visibility: hidden;
            transform: translate3d(0, 100%, 0);
        }
    }
    
    .modal {
        position: fixed;
        z-index: 10;
        left: 0;
        right: 0;
        bottom: 0;
        top: 0;
        width: 100%;
        height: 100%;
        background-color: white;
    }

    .modal-enter {
        animation: slideInUp .5s cubic-bezier(0.23,1,0.32,1);
    }

    .modal-leave {
        animation: slideOutDown .35s cubic-bezier(0.23,1,0.32,1);
    }

}
```
compiles to:
```css
@keyframes src-components-Modal-___Modal__slideInUp___xjx2Y {
  from {
    transform: translate3d(0, 100%, 0);
    visibility: visible;
  }

  to {
    transform: translate3d(0, 0, 0);
  }
}

@keyframes src-components-Modal-___Modal__slideOutDown___2zyuP {
  from {
    transform: translate3d(0, 0, 0);
  }

  to {
    visibility: hidden;
    transform: translate3d(0, 100%, 0);
  }
}

.modal {
  position: fixed;
  z-index: 10;
  left: 0;
  right: 0;
  bottom: 0;
  top: 0;
  width: 100%;
  height: 100%;
  background-color: white;
}

.modal-enter {
  animation: slideInUp 0.5s cubic-bezier(0.23, 1, 0.32, 1);
}

.modal-leave {
  animation: slideOutDown 0.35s cubic-bezier(0.23, 1, 0.32, 1);
}
```
This is incorrect, right? Notice how the class names are not being changed but the keyframes are.

**Comment by psimyn** [comment]
Might need different handling for keyframes.

Try `@keyframes :global(slideInUp) {}` (doesn't need to be nested in the other global)

Not sure if this is doc'd but saw it in a test

**Comment by dwilt** [comment]
Thanks for the idea. Didn't work though :(

```css
@keyframes :global(slideInUp) {
    from {
        transform: translate3d(0, 100%, 0);
        visibility: visible;
    }

    to {
        transform: translate3d(0, 0, 0);
    }
}

@keyframes :global(slideOutDown) {
    from {
        transform: translate3d(0, 0, 0);
    }

    to {
        visibility: hidden;
        transform: translate3d(0, 100%, 0);
    }
}

@keyframes :global(fadeIn) {
    from {
        opacity: 0;
    }

    to {
        opacity: 1;
    }
}

@keyframes :global(fadeOut) {
    from {
        opacity: 1;
    }

    to {
        opacity: 0;
    }
}
```

threw this:
```
WARNING in ./~/css-loader?modules&importLoaders=1&localIdentName=[path]___[name]__[local]___[hash:base64:5]!./~/resolve-url-loader!./~/sass-loader!./src/components/Modal/Modal.scss
  resolve-url-loader cannot operate: CSS error
  /Users/dwilt/Projects/64i/64i-v2/src/components/Modal/Modal.scss:1:12: @keyframes missing name
  at error (/Users/dwilt/Projects/64i/64i-v2/node_modules/css/lib/parse/index.js:62:15)
```
