### ISSUE TITLE
& + & in local scope causes error

### ISSUE THREAD

**Issue by iotch** [webpack-contrib/css-loader#276]
Hello.

I'm getting "Missing whitespace before :local" error when referencing parent selector with an ampersand as adjacent sibling selector, for example:

``` scss
:local {
    .root {
        color:red;

        & + & {
            color:black;
        }
    }
}
```

Making rules globally works as expected, so it seems like a bug.

I'm expecting to have `.[hash] + .[hash] { color:black }` as the output. If this is an expected behaviour, how should I write such rules? 

Thanks.
