### ISSUE TITLE
cssnano option orderedValues conflicts with css-modules imports

### ISSUE THREAD

**Issue by wereHamster** [webpack-contrib/css-loader#316]
The cssnano optimization **orderedValues** uses the `postcss-ordered-values` module to process the CSS AST and normalizes `border: X` declarations. It tries to parse the right-hand of `border:` and extract the width, style and color. It parse the width using `postcss-value-parser`. However, when the `border:` declaration contains values imported from another file, cssnano sees strings like `___CSS_LOADER_IMPORT___7___` instead of the pixel values. So `postcss-value-parser` fails to parse the width and drops it form the output.

In my case, I have a this CSS code:

``` css
@value selectInputBorderWidth, selectInputBorderColor from "./variables.css";
.Select-control {
    border: selectInputBorderWidth solid selectInputBorderColor;
}
```

and the output is:

``` css
.Select-control {
    border: solid #666666;
}
```

cssnano does not (and can not, at that stage in the webpack loader pipeline) see the faithful representation of the CSS code with all values and imports fully resolved. I can try to disable **orderedValues** (which solves this particular bug in my particular instance) but I do wonder which other optimizations are unsafe. The safest option is to remove cssnano completely from css-loader.

TLDR: remove cssnano, it can not work reliably.
