### ISSUE TITLE
Automatically verify class name existence

### ISSUE THREAD

**Issue by frenic** [webpack-contrib/css-loader#326]
Composing a non-existing selector causes `webpack-dev-server@1.15.1` too freeze without error and causes `webpack@1.13.2` to abort without error.

``` css
.foobar {
  composes: non-existing;
}
```

The build succeeds when composing an external CSS module, but no error appears.

``` css
.foobar {
  composes: non-existing from './another-existing-css-module.css';
}
```

Feels to me that it should at least throw some kind of error?
