### ISSUE TITLE
Trouble with scss and nested selectors

### ISSUE THREAD

**Issue by coljung** [webpack-contrib/css-loader#346]
So, I was trying to achieve something like

``` css
.pagination{
    display:flex;
    justify-content: center;
    ...
    li{
        border: 1px solid #ccc;
        ...
    }
    a{
        display: block;
        padding: 10px 15px;
        ...
    }
    .active {
        a{
            background: #eee;
            ...
        }
    }

}
```

Im using React btw, and also using a library based on material design called react-toolbox. React toolbox is using css-modules to manage CSS.

I basically create my scss file, then import them into my component and assign them like {style.pagination} for example.

Now my problem is that this approach works well including the nested selectors 'without' any classes. In the above example, **'.active a'** doesnt work at all and i have no idea how to solve this. It does work only if i resort to using the 'global:' flag.

In this particular case, it is not that much of a problem using the :global flag, but i had other cases where i had to target elements to which i had no control over classnames, and even using :global wouldnt help.

**Comment by seleckis** [comment]
I have the same problem with nested classes.

**Comment by seleckis** [comment]
The only way I've found is to make nested selector global:
```scss
.pagination{
    display:flex;
    justify-content: center;
    ...
    li{
        border: 1px solid #ccc;
        ...
    }
    a{
        display: block;
        padding: 10px 15px;
        ...
    }
    :global .active {
        a{
            background: #eee;
            ...
        }
    }

}
```
