### ISSUE TITLE
Source map is incorrect when url()'s is rewrited

### ISSUE THREAD

**Issue by x-yuri** [webpack-contrib/css-loader#379]
`package.json`:

```js
{
  "dependencies": {
    "css-loader": "^0.26.0",
    "file-loader": "^0.9.0",
    "html-webpack-plugin": "^2.24.1",
    "style-loader": "^0.13.1",
    "webpack": "^1.13.3"
  }
}
```

`webpack.config.js`:

```js
var HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
    entry: './1.js',
    output: {
        path: 'dist',
        filename: 'bundle.js',
    },
    module: {
        loaders: [
            {test: /\.css$/, loaders: ['style', 'css?sourceMap&minimize']},
            {test: /\.png$/, loader: 'file'},
        ]
    },
    plugins: [
        new HtmlWebpackPlugin({
            template: 'template.ejs',
        }),
    ],
};
```

`template.ejs`:

```html
<!doctype html>
<html>
<body>

    <div class="d1"></div>
    <div class="d2"></div>

</body>
</html>
```

`1.js`:

```js
require('./1.css');
```

`1.css`:

```css
.d1 {
    background: url(1.png);
}
.d2 {
    width: 20px;
}
```

```sh
$ npm i
$ rm -rf dist/* && ./node_modules/.bin/webpack
```

Then open `http://example.com/dist` in Chrome. Then `Developer Tools` > `Elements tab`. Then click on second `div`, and then on the link for `.d2 { width: 20px; }` rule. And you'll find yourself on line 5. But if you remove `minimize` param, you'll be at line 4, which is as it should be.

P.S. node-7.1.0, Arch Linux

**Comment by x-yuri** [comment]
I now see, [here][1] we've got the following css (as json):

```js
".d1{background:url(___CSS_LOADER_URL___0___)}.d2{width:20px}"
```

and mappings:

```
AAAA,IACI,wCAAuB,CAC1B,AACD,IACI,UAAY,CACf

([0,0](#0)=>[0,0])
    | ([1,4](#0)=>[0,4])
    | ([1,27](#0)=>[0,44])
    | ([2,1](#0)=>[0,45])
    | ([3,0](#0)=>[0,45])
    | ([4,4](#0)=>[0,49])
    | ([4,16](#0)=>[0,59])
    | ([5,1](#0)=>[0,60])
```

which are totally correct. You must already see, where this is coming. Now then, [this block][2] changes css from

```js
".d1{background:url(___CSS_LOADER_URL___0___)}.d2{width:20px}"
```

to

```js
".d1{background:url(" + require("./1.png") + ")}.d2{width:20px}"
```

which then gets replaced with `__webpack_require__(4)` in the resulting bundle. But source map is never updated since being generated, so no surprise it's wrong.

[1]: https://github.com/webpack/css-loader/blob/v0.26.0/lib/loader.js#L34
[2]: https://github.com/webpack/css-loader/blob/v0.26.0/lib/loader.js#L69-L85

**Comment by evilebottnawi** [comment]
Closing due to inactivity. Please test with latest version and feel free to reopen if still regressions. Thanks!

**Comment by x-yuri** [comment]
@evilebottnawi Yeah, I can reproduce it with `webpack@^3.0.0`. Here's [the archive](https://github.com/webpack-contrib/css-loader/files/1755881/img-urls.zip) with files needed to reproduce the issue.

`1.css`
```css
.d1 {
    background: url(1.png);
}
.d2 {
    width: 20px;
    height: 20px;
}
.d3 {
    width: 30px;
    height: 30px;
}
.d4 {
    width: 40px;
    height: 40px;
}
```

The thing is [here][after-process-css] we get totally valid source map:

[after-process-css]: https://github.com/webpack-contrib/css-loader/blob/v0.28.10/lib/loader.js#L52

```css
.d1{background:url(___CSS_LOADER_URL___0___)}.d2{width:20px;height:20px}.d3{width:30px;height:3
0px}.d4{width:40px;height:40px}                                                
                                                                  
/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjp
bIi4uLy4uLy4uLy4uL2Nzcy1sb2FkZXIhL3Nydi9odHRwL3MxL2ltZy11cmxzLzEuY3NzIl0sIm5hbWVzIjpbXSwibWFwcG
luZ3MiOiJBQUFBLElBQ0ksd0NBQXVCLENBQzFCLEFBQ0QsSUFDSSxXQUFZLEFBQ1osV0FBYSxDQUNoQixBQUNELElBQ0ksV
0FBWSxBQUNaLFdBQWEsQ0FDaEIsQUFDRCxJQUNJLFdBQVksQUFDWixXQUFhLENBQ2hCIiwiZmlsZSI6IjEuY3NzIiwic291
cmNlc0NvbnRlbnQiOlsiLmQxIHtcbiAgICBiYWNrZ3JvdW5kOiB1cmwoMS5wbmcpO1xufVxuLmQyIHtcbiAgICB3aWR0aDo
gMjBweDtcbiAgICBoZWlnaHQ6IDIwcHg7XG59XG4uZDMge1xuICAgIHdpZHRoOiAzMHB4O1xuICAgIGhlaWdodDogMzBweDtcbn1cbi5kNCB7XG4gICAgd2lkdGg6IDQwcHg7XG4gICAgaGVpZ2h0OiA0MHB4O1xufVxuIl19 */
```

Open [SourceMap Inspector][source-map-inspector], put it into Output field, click Analyze, use Left, Right arrow buttons.

[source-map-inspector]: http://libsass.ocbnet.ch/srcmap/

But then [this block of code][replace-url-placeholders] turns it into:

```css
".d1{background:url(" + escape(require("./1.png")) + ")}.d2{width:20px;height:20px}.d3{width:30px;height:30px}.d4{width:40px;height:40px}"
```

[replace-url-placeholders]: https://github.com/webpack-contrib/css-loader/blob/v0.28.10/lib/loader.js#L90-L110

And in the bundle we've got:

```css
exports.push([module.i, ".d1{background:url(" + escape(__webpack_require__("./1.png")) + ")}.d2{width:20px;height:20px}.d3{width:30px;height:30px}.d4{width:40px;height:40px}"...
```

`escape(__webpack_require__("./1.png"))` gets replaced with something similar to `52647b79be294c690caeecc2fa55ef92.png`. Then it's converted [to absolute url][to-abs-url], but source map was never updated since we got it in `processCss`'s callback.

[to-abs-url]: https://github.com/webpack-contrib/style-loader/blob/v0.20.2/lib/addStyles.js#L361

And then:

![](https://i.imgur.com/MjghM1u.png)
![](https://i.imgur.com/YpUb7F8.png)

But when I comment out the `background: url(1.png);` line, I get:

![](https://i.imgur.com/mMHQsUl.png)
![](https://i.imgur.com/n5mURJF.png)

P.S. Most likely, it's not only about image urls. Here's [another thing][replace-imports] that changes css code without updating source map.

[replace-imports]: https://github.com/webpack-contrib/css-loader/blob/v0.28.10/lib/loader.js#L85
