### ISSUE TITLE
EQCSS: Selectors within element queries are not recognized

### ISSUE THREAD

**Issue by sunny-g** [webpack-contrib/css-loader#387]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
Loader doesn't parse all selector references when using [Element Queries](https://github.com/eqcss/eqcss)

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Add element queries to your CSS and inspect the output

**What is the expected behavior?**
All selector references will be "picked up" and hashed by css-loader.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**
Webpack v1.13.3
Node v6.3.1
npm v3.10.3

-----
input css:
```css
/* give .myDiv a red background if at it is at least 300px wide */
@element ".myDiv" and (min-width: 300px) {    /* quotes have made no difference */
  .myDiv {
    background: red;
  }
}
```

expected output css:
```css
@element .myDiv_3lk2h and (min-width: 300px) {
  .myDiv_3lk2h {
    background: red;
  }
}
```

actual output css:
```css
@element .myDiv and (min-width: 300px) {
  .myDiv_3lk2h {
    background: red;
  }
}
```

Wrapping the first reference to the selector in quotes, `:local(.myDiv)`, PostCSS nested selectors, nor using custom selectors from the PostCSS plugin seem to make any difference.

See for more information: https://github.com/css-modules/css-modules/issues/169
