### ISSUE TITLE
Request feature: Add option to compile only top-level selectors in css-modules mode

### ISSUE THREAD

**Issue by mizchi** [webpack-contrib/css-loader#423]
I use [postcss-nesting:https://github.com/jonathantneal/postcss-nesting] plugni ( implementation of CSS Nesting Module Level 3 ) and css-loader v0.26.1.

MyCode

```css
.Hello {
  & .title {
    color: #00f;
  }
}
```

Compiled with css-loader?modules
```css
._1yKwJThgxBsO6G-dlD__k6 {
}
._1yKwJThgxBsO6G-dlD__k6 ._2jGR-DRZ3K4plA7FSjgwvJ {
  color: #00f
}
```

All selector are flattened so I have to write like this.

```js
import React from 'react'
import styles from './styles.css'
export default function Hello () {
  return <div className={styles.Hello}>
    <div className={styles.title}>Hello</div>
  </div>
}
```

But I want to write like next one.

```js
  return <div className={styles.Hello}>
    <div className="title">Hello</div>
  </div>
```

So my expected behaviour is 

```
._1yKwJThgxBsO6G-dlD__k6 {
}
._1yKwJThgxBsO6G-dlD__k6 .title {
  color: #00f
}
```

or `styles.Hello.title` (it will be hacky implementation of getter by Reflect)

To keep css moduleness, I think it's enough to convert top-level selectors and easy for css animation.

How do you think? (or already has other way of this?)
