### ISSUE TITLE
css-module composes from other module not working.

### ISSUE THREAD

**Issue by mrdulin** [webpack-contrib/css-loader#443]
`webpack.config.js`:
```js
{
        test: /\.module\.(scss|css)$/,
        include: /\.module\.(scss|css)$/,
        loader: ExtractTextPlugin.extract('style', `css?${JSON.stringify(cssLoaderQuery)}!sass?sourceMap`)
      },
      {
        test: /\.scss$/,
        exclude: [/node_modules/, /\.module\.(scss|css)$/],
        loader: ExtractTextPlugin.extract('style', `css?sourceMap!sass?sourceMap`)
      }
```

`src/index.module.scss`:

```scss
.button-primary{
    composes: button from './common/sass/button.scss';
    background: lightblue;
}

.link-small{
    // composes: link from './common/sass/link.css';
    composes: link from 'common/sass/link.module.css';
    font-size: 14px;
}

.list-m{
    composes: list from 'common/sass/list.module.scss';
    border: 1px solid #ddd;
}
```
All of `composes` not working. No matter I use `alias` or `relative path`. 

My project directory structure: 

![](http://ww1.sinaimg.cn/mw690/005FHMJXgy1fdf9cdy4q8j30dw0fogmx)

-- update 2017.04.11 ---

Here is my `webpack.config.js`:  https://github.com/mrdulin/webpack1.x/blob/master/css-loader/css-module-import-module/webpack.config.js

the issue still exist.
