### ISSUE TITLE
JS modules can be imported and executed from CSS

### ISSUE THREAD

**Issue by darrenscerri** [webpack-contrib/css-loader#462]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
Although this might be intended, it might not be correct to require certain files such as Javascript files from CSS.

**If the current behavior is a bug, please provide the steps to reproduce.**
See this repo for more information: https://github.com/darrenscerri/webpack-extract-text-plugin-empty-require-error.

Related issues:
https://github.com/webpack/webpack/issues/4541
https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/465

**Comment by michael-ciniawsky** [comment]
Fixed by #513

**Comment by evilebottnawi** [comment]
@darrenscerri Problem still exists?

**Comment by evilebottnawi** [comment]
Confirm.
Input:
```css
a {
  background-image: url("");
}
```

Output:
```css
a {
  background-image: url("https://example.com/");
}
```
