### ISSUE TITLE
CSS Scoping For React Components

### ISSUE THREAD

**Issue by bigfanjs** [webpack-contrib/css-loader#490]
**Do you want to request a *feature* or report a *bug*?**
*feature*

**What is the current behavior?**
For CSS modules/scoping that css-loader offers both come with expensive costs; You whether need to pollute your CSS or to assign imported class names everywhere in your components.

**What is the expected behavior?**
Importing a CSS file to its component and Webpack automatically apply scoping.

**If this is a feature request, what is motivation or use case for changing the behavior?**
First of all I badly need this. Well, I am not sure if that is even possible but I think if we take the imported styles for each component and prefix their current selector names with where it's located in the directory structure as long as each component has its own unique path(even if this is not true we can index those sharing the same path). For Html elements I think separately applying an instance of the same process whether through adding a loader or a babel plugin would work.

For example:

The directory structure: 
```
├── shared
    ├── footer
        ├── footer.js
        ├── footer.test.js
        ├── footer.css
        └── index.js
```

./shared/footer.css
````css
.footer {
   background-color:  black;
   position: absolute;
   width: 100%;
   bottom: 0;
}
````

./shared/footer.js
````js
import React from 'react';

// import styles.
import './footer.css';

export default function () {
   return () {
        <div className="footer"></div>
   }
}
````

And the generated code has to be something like this:

./shared/footer.css
````css
/*prefix the css selector with the path*/
.shared_footer {
   background-color:  black;
   position: absolute;
   width: 100%;
   bottom: 0;
}
````

./shared/footer.js
````js
import React from 'react';

// import styles.
import './footer.css';

export default function () {
   // prefix class names
   return <div className="shared_footer"></div>
}
````
