### ISSUE TITLE
css-loader should understand global aliases

### ISSUE THREAD

**Issue by kud** [webpack-contrib/css-loader#522]
I've got: 

```javascript
    resolve: {
      alias: {
        '~': `${SRC_DIR}`,
      }
    },
```

It could be great if I was directly able to do: 

```css
.test {
  composes: base from '~/file.css';
}
```

without having to define aliases for css-loader.
