### ISSUE TITLE
getLocalIdent doesn't apply for composed classes

### ISSUE THREAD

**Issue by eloytoro** [webpack-contrib/css-loader#524]
**Do you want to request a *feature* or report a *bug*?**
It's a bug

**What is the current behavior?**
`getLocalIdent` works for all directly required css file, but doesn't for composed classes

**If the current behavior is a bug, please provide the steps to reproduce.**

Loader in the webpack config
```js
{
  test: /\.css$/,
  loader: 'css-loader',
  options: {
    modules: true,
    importLoaders: 1,
    getLocalIdent: () => 'foo'
  }
}
```

style1.css
```css
.bar {
  composes: baz from './style2.css';
  color: white;
}
```

style2.css
```css
.baz {
  background: red;
}
```

module.js
```js
require('./style1.css') // { 'bar': 'foo _3eS695' }
```

**What is the expected behavior?**

module.js
```js
require('./style1.css') // { 'bar': 'foo foo' }
```

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**

css-loader@0.26.1
webpack@2.4.1
