### ISSUE TITLE
Composes does not work with css-loader/locals

### ISSUE THREAD

**Issue by DylanPiercey** [webpack-contrib/css-loader#537]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Currently when you use `composes: x from './y.css'` using the `css-loader/locals` plugin for server side rendering it creates a circular dependency no matter what.

**If the current behavior is a bug, please provide the steps to reproduce.**
Loader config:
```js
{
  test: /\.css$/,
  exclude: /node_modules/,
  use: {
    loader: 'css-loader/locals',
    modules: true,
    sourceMap: true
  }
}
```

**What is the expected behavior?**
That only a circular dependency would error. (Note there is no error displayed any required module just will not resolve).

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**
webpack v2x, node 7, macOS

**Comment by pixelass** [comment]
I'm not sure if this is related but composes from another file seem not to be resolved.


```less
.wrapper {
	composes: grid from './foo.less';
}

.nav {
	composes: wrapper;
	/* footer nav element */
}

.socialNav {
	/* footer social nav element */
}

.brandNav {
	/* footer brand nav element */
}
```


```js
// exports
exports.locals = {
	"wrapper": "e9oiFTlAUxvsYfN3AXVAS " + require("-!../../../../../../../node_modules/css-loader/index.js?{\"modules\":true,\"sourceMap\":true}!./foo.less").locals["grid"] + "",
	"nav": "bUQCLkB65igesOUztxpHc e9oiFTlAUxvsYfN3AXVAS " + require("-!../../../../../../../node_modules/css-loader/index.js?{\"modules\":true,\"sourceMap\":true}!./foo.less").locals["grid"] + "",
	"socialNav": "_2q5ZQPrp57ZlshW3-oXSG-",
	"brandNav": "_36BcBteQRXzJN_Cv-6lehZ"
};
```
