### ISSUE TITLE
How to ignore specific url

### ISSUE THREAD

**Issue by Eugene-Kotovich-EPAM** [webpack-contrib/css-loader#538]
Hello. I want to know how to ignore specific url.
Using option `url: false` doesn't help, because it disable resolving of all `url` usage. Also the usage of `/` doesn't help.
Is it possible enable ignoring for specific path? Like below:
```scss
.some-class {
  background: url("../../specific-folder/some-image.png") // want to output url with specific-folder as is
}
```

Thanks.
