### ISSUE TITLE
Incorrectly minifying class names with containing certain color words

### ISSUE THREAD

**Issue by jaredlunde** [webpack-contrib/css-loader#554]
**Do you want to request a *feature* or report a *bug*?**
Report a bug (0.28.4)

**What is the current behavior?**
These classes:
```css
.type--yellow{color:#ffc952}
.type--black{color:#2c2829}
.type--white{color:#fefeff}
```
are incorrectly minifying to:
```css
.type--#ff0{color:#ffc952}
.type--#000{color:#2c2829}
.type--#fff{color:#fefeff}
```

This only occurs when the minifier is turned on.

**If the current behavior is a bug, please provide the steps to reproduce.**
Here is my relevant webpack configuration:
```js
{
  test: /\.scss$/,
  use: extractSass.extract({
    fallback: 'style',
    use: [
       'css',
       'sass'
    ]
  })
}
```

**What is the expected behavior?**
Class names should not be minified

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**
*webpack* version: 2.6.1
*css-loader* version: 0.28.4
*node* version: 8.1.0
*OS*: macOS Sierra 10.12.5

**Comment by TrySound** [comment]
Do you define values named yellow, black and white?

**Comment by jaredlunde** [comment]
In SCSS? Yes.

```scss
$black: #2c2829;
$white: #fefeff;
$yellow: #ffc952;
```

For some reason, black, yellow, and white are the only colors where this is happening. Blue, red, green, grey, etc. don't get replaced.

It's also worth noting that this happens throughout the CSS document, not just in one particular spot. So there are also replacements like:

```css
.btn--#ff0 button.active,
.btn.btn--#ff0.active {
    background: #ffc139
}
.no-touchevents .btn--#ff0 .btn.hover,
.no-touchevents .btn--#ff0 .btn:hover,
.no-touchevents .btn--#ff0 button.hover,
.no-touchevents .btn--#ff0 button:hover,
.no-touchevents .btn.btn--#ff0.hover,
.no-touchevents .btn.btn--#ff0:hover {
    background: #ffd16c
}
```

Would it be helpful to see the entire node-sass'd stylesheet (which compiles correctly) in addition to the entire malformed stylesheet that is output by the minifier?
