### ISSUE TITLE
Imported local aliases not working when used in selectors

### ISSUE THREAD

**Issue by apexskier** [webpack-contrib/css-loader#561]
Reporting https://github.com/css-modules/icss/issues/12 for visibility. I'll copy the details, but I'm experiencing the exact same issue.

**Do you want to request a *feature* or report a *bug*?**
bug report

**What is the current behavior?**
```css
// foo.scss
.foo {
    color: blue;
}

// bar.css
:import("foo.css") {
    fooClassName: foo;
}
.fooClassName .bar { // <-- this doesn't get replaced :(
    color: red;
}

// baz.css
:import("foo.css") {
    fooClassName: foo;
}
.baz {
    color: fooClassName; // <-- this does get replaced :)
}
```

**What is the expected behavior?**
`fooClassName` is replaced with the local name for `foo` from `foo.css` in both `bar.scss` and `baz.scss

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**
I'm currently testing with webpack 2.2.1, node 7.2.1, css-loader 0.28.4.
