### ISSUE TITLE
broken escaping

### ISSUE THREAD

**Issue by eeve** [webpack-contrib/css-loader#578]
**What is the current behavior?**
 The escape symbol `\` was lost
```css
.grid            { display: flex; flex-wrap: wrap; }
.grid.\-top      { align-items: flex-start; }
.grid.\-middle   { align-items: center; }
.grid.\-bottom   { align-items: flex-end; }
```
=>

```css
.grid            { display: flex; flex-wrap: wrap; }\n.grid.-top      { align-items: flex-start; }\n.grid.-middle   { align-items: center; }\n.grid.-bottom   { align-items: flex-end; }\n
```

**What is the expected behavior?**
Keep the escape symbol `\`

https://github.com/eeve/test.v1

**Comment by evilebottnawi** [comment]
@eeve btw, why your use `\` in `selectors`

**Comment by jschlieber** [comment]
I'm running into the exact same issue. In my case escape sequences are used in Predix-UI CSS Modules, e.g:

https://github.com/PredixDev/px-spacing-design/blob/db32341b44fee68cace50d5d236306f768bbed26/_trumps.spacing.scss#L175-L181

So that basically means I can't use those `u-m+` and `u-m++` classes.

Any ideas for a quick workaround?

**Comment by evilebottnawi** [comment]
@jschlieber unfortunately no, try to found and fix problem today

**Comment by jschlieber** [comment]
@evilebottnawi Any news on this issue?

**Comment by evilebottnawi** [comment]
@jschlieber I was on vacation, in the near future I will take care of this, thanks for waiting

**Comment by evilebottnawi** [comment]
@jschlieber `u-m+` and `u-m++` invalid css classes (https://jigsaw.w3.org/css-validator/validator), your should use `u-m\+` and `u-m\+\+`

**Comment by evilebottnawi** [comment]
@jschlieber also `.\-top {}` and `.-top {}` are valid class selectors and mean the same thing.

**Comment by evilebottnawi** [comment]
Bug inside `postcss-modules-local-by-default` and `postcss-modules-scope`, they remove `\` character. But i wonder use case. 

@jschlieber `.u-m\+` and etc selectors work good (https://github.com/webpack-contrib/css-loader/pull/584).

@TrySound what do your think about this?

**Comment by jschlieber** [comment]
@evilebottnawi Ok, but what you're telling me is that i can't define my css selector as:
```css
.u-m++{
  ...
}
```
and I'm totally fine with that. But still, if classes are defined like this
```css
.u-m\00002b{
  ...
}
```
as in the PredixUi CSS library (which btw is valid css). I can't use it like it is intended, e.g.
```html
<div class="u-m+">
  ...
</div>
```
because it ends up as
```css
.u-m00002b{
  ...
}
```
so I would have to use it like this
```html
<div class="u-m00002b">
  ...
</div>
```

**Comment by evilebottnawi** [comment]
@jschlieber don't understand your. Your can use `.u-m\00002b` in your css and `css-loader` works fine. 
Input:
```css
.u-m\00002b {
    border: 10px solid black;
}
```

Output:
```css
.u-m\00002b {
  border: 10px solid black;
}
```

Just try to test in your project.
I agree what `css-loader` should not remove `\`, but it is happens only with selector where escaped is not necessary (example if your have `\.-top {}`, your can use `.-top {}`, because `\.-top {}` and `.-top {}` are mean the same thing).

**Comment by evilebottnawi** [comment]
@jschlieber Thanks for issue, confirmed. Let's wait what says @TrySound (he have access for `postcss-*` plugins for `css-loader`)

**Comment by jschlieber** [comment]
@evilebottnawi Thanks for your efforts. Any news on this one?

**Comment by evilebottnawi** [comment]
@jschlieber no :disappointed: 
@TrySound friendly ping

**Comment by TrySound** [comment]
I guess it's something in selector tokenizer. Patch release will help. However I don't have access yet.

**Comment by TrySound** [comment]
https://github.com/css-modules/css-selector-tokenizer

**Comment by 6palace** [comment]
+1 from us as well

**Comment by RoopGuron** [comment]
+1 This fix is needed.

**Comment by EvanLovely** [comment]
I've got a workaround [detailed here](https://github.com/bolt-design-system/bolt/pull/410)

**Comment by EvanLovely** [comment]
I found where this is being caused: [`./lib/getLocalIndent.js` has a `.replace()` function](https://github.com/webpack-contrib/css-loader/blob/630579d01e9d28a2032e707dcea2ad9f4ec613da/lib/getLocalIdent.js#L15:73) that replaces a big RegEx with `-` (if you change that character and run you can see it being used).

**Comment by EvanLovely** [comment]
It appears that by the time it hits this file, classes like `.u-hide\@large` are already `.u-hide@large`, and then after that line become ``.u-hide-large`.

**Comment by EvanLovely** [comment]
Hmm... also turning CSS modules off with `options.modules = false` "fixes" it.

**Comment by evilebottnawi** [comment]
Just infromation:
```css
.icon-caret-left:before {
   content: '"\\f10c"'
}
```

Also broken

**Comment by evilebottnawi** [comment]
Also
```css
body {
  font-family: '微软雅黑'; /* some chinese font name */
}
```
