### ISSUE TITLE
CSS modules break build if used with `~`

### ISSUE THREAD

**Issue by jantimon** [webpack-contrib/css-loader#589]
> Module not found: Error: Can't resolve '~'

**What is the current behavior?**

Using a tilde `~` inside a css file causes `Can't resolve '~'` if css-modules feature is activated:

```js
{
  loader: 'css-loader',
  options: {
    modules: true,
  }
},
```

**If the current behavior is a bug, please provide the steps to reproduce.**

The bug can be reproduced this way: (https://github.com/jantimon/css-loader-bug)

```bash
git clone https://github.com/jantimon/css-loader-bug.git
cd css-loader-bug
npm install
npm run without-modules 
npm run with-modules
```

[Working webpack.config.js](https://github.com/jantimon/css-loader-bug/blob/master/without-modules/webpack.config.js)
[Broken webpack.config.js](https://github.com/jantimon/css-loader-bug/blob/master/with-modules/webpack.config.js)
[CSS File](https://github.com/jantimon/css-loader-bug/blob/master/index.css#L3)

**What is the expected behavior?**

Compilation should work even if `modules` are set to true.

**Motivation**

I wrote a loader which adds `~!!` to a css file and it does not know if the user is using css-modules: https://github.com/jantimon/iconfont-webpack-plugin/blob/master/lib/postcss-plugin.js#L135-L137

**Comment by evilebottnawi** [comment]
@jantimon why don't use `url('file-loader!flags-of-the-world/src/DK.svg')`?

**Comment by jantimon** [comment]
@evilebottnawi this won't work if `modules` are set to false.

**Comment by jantimon** [comment]
For now I am working around this issue by forcing the user to tell me wether he is using cssModules or not:

https://github.com/jantimon/iconfont-webpack-plugin/blob/master/example/module/webpack.config.js#L30

**Comment by lcsrinaldi** [comment]
Is this considered an inconsistency? I wish I could fix this.

**Comment by lnhrdt** [comment]
> Is this considered an inconsistency?

Yes, it definitely is. I believe this also may be the cause of some confusion in issues like #12.

**Comment by evilebottnawi** [comment]
Seems bug PR welcome!

**Comment by evilebottnawi** [comment]
Just information: `@import "~normalize.css/normalize.css";` also don't works, seems all syntax don't workds

**Comment by Oscar-ren** [comment]
I find the reason: https://github.com/webpack-contrib/css-loader/blob/master/lib/processCss.js#L163-L174
If open the css module, the mode is 'local', url will reserve the `~`,such as:
```css
:local { * { background: url('~assets/my-asset.svg'); } }
// urlToRequest
:local { * { background: url(require('~assets/my-asset.svg')); } }
``` 
else the mode is 'global', url will recognize the `~` ,https://github.com/webpack/loader-utils/blob/67499ff3d13c13ef455ec0fede90b714fc16d787/lib/urlToRequest.js#L50-L52,and remove the `~`,require file as a module.such as:
```css
:global { * { background: url('~assets/my-asset.svg'); } }
// urlToRequest
:global { * { background: url(require('assets/my-asset.svg')); } }
```
