### ISSUE TITLE
Composing a class from a different file does not pass that class through `getLocalIdent`

### ISSUE THREAD

**Issue by pillowfication** [webpack-contrib/css-loader#636]
**What is the current behavior?**
Composing a class from a different file does not pass that class through `getLocalIdent`.

```javascript
use: [{
  loader: 'css-loader',
  options: {
    modules: true,
    importLoaders: 2,
    localIdentName: '[local]',
    getLocalIdent: (context, localIdentName, localName, options) => 'prefix-' + localName,
}, {
  loader: 'sass-loader'
}]
```

```scss
// foo.scss
.foo { color: red; }

// bar.scss
.bar { composes: foo from "./foo.scss"; }
```

```javascript
import styles from './bar.scss'
console.log(styles.bar)
// -> "prefix-bar foo"
```

**What is the expected behavior?**
I expected the same behavior as I would get when I compose from the same file.

```scss
// bar.scss
.foo { color: red; }
.bar { composes: foo; }
```

```javascript
import styles from './bar.scss'
console.log(styles.bar)
// -> "prefix-bar prefix-foo"
```
