### ISSUE TITLE
What is the syntax of using module and sass @at-root together?

### ISSUE THREAD

**Issue by aixfox** [webpack-contrib/css-loader#666]
Hi,
  It seems that css-loader works not well with sass @at-root.
  Examples with 'module: true' below:
Writen like this:
```scss
.foo {
  .bar {
    color: red
    @at-root :global(.ie) :local(&) { color: blue }
  }
}
```
Exp:
```css
.foo_hash1 .bar_hash2 { color: red  }
.ie .foo_hash1 .bar_hash2 { color: blue }
```

And writen:
```scss
:global {
  @at-root .ie { color: blue }
}
```
It still compiles to .ie_hash like with writen :local;
