### ISSUE TITLE
Incorrect transformation of transition name

### ISSUE THREAD

**Issue by cfv1984** [webpack-contrib/css-loader#699]
Using Webpack 4 and css-loader@0.28.11, I get incorrect CSS output from correct CSS input

**Do you want to request a *feature* or report a *bug*?**
*Bug*

**What is the current behavior?**
```scss 
// input
.root {
  display: inline-block;
  line-height: 3em;
  padding: 0 1em;
  font-size: 14px;
  color: black;
  animation: 1s LoadingAnimation infinite;
}

@keyframes LoadingAnimation {
  0% {
    background: brown;
  }
  50% {
    background: red;
  }
  100% {
    background: brown;
  }
}

// output 
._1F-NQ31U-OsaGN5_F8NNk1 {
  display: inline-block;
  line-height: 3em;
  padding: 0 1em;
  font-size: 14px;
  color: black;
  animation: 1s :local(LoadingAnimation) infinite; }

@keyframes _2lYftgHXJ9VFhNBkK-QW_D {
  0% {
    background: brown; }
  50% {
    background: red; }
  100% {
    background: brown; } }
```

what even is this :local() thing doing here?

**If the current behavior is a bug, please provide the steps to reproduce.**

This are the loaders I'm using in webpack: 

```js
    module: {
        rules: [
            {test: /\.tsx?$/, use: [{loader: "ts-loader"}]},
            {
                test: /\.scss$/,
                use: [{
                    loader: "style-loader",

                }, {
                    loader: 'css-loader',
                    options: {
                        modules: true,
                    }
                }, {
                    loader: "sass-loader",
                    options: {
                    }
                }]
            }
        ],
    },
```
**What is the expected behavior?**

Actual, valid and usable CSS is produced. 

**If this is a feature request, what is motivation or use case for changing the behavior?**

Not a feature request, I just want to use CSS modules

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**

| | Version                                |
|------------|---------------------------|
|   webpack  | 4.4.1                                    |
|   node         | v9.10.0                      |
|     os:          | OSX 10.13.3    |
