### ISSUE TITLE
Incorrect behaviour with media-query

### ISSUE THREAD

**Issue by smelukov** [webpack-contrib/css-loader#700]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Adds all composes classes from the style and ignores media-queries

**If the current behavior is a bug, please provide the steps to reproduce.**

```css
@media (max-width: 576px) {
    .size-s {
        composes: width-8 from '../grid/width.css';
    }

    .size-m {
        composes: width-10 from '../grid/width.css';
    }

    .size-l {
        composes: width-12 from '../grid/width.css';
    }
}

@media (min-width: 576px) {
    .size-s {
        composes: width-6 from '../grid/width.css';
    }

    .size-m {
        composes: width-8 from '../grid/width.css';
    }

    .size-l {
        composes: width-10 from '../grid/width.css';
    }
}
```

```jsx
import styles from './style.css';

// ...

<div className={styles['size-l']} />
```

Then resize browser window to 1000px and get the result:
```html
<div class="size-l-1-oLr width-12-2A9DS width-10-3s4HR"/>
```

**What is the expected behavior?**

```html
<div class="size-l-1-oLr width-10-3s4HR"/>
```

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**

Webpack: 3.11.0
css-loader: 0.28.0
