### ISSUE TITLE
Should not resolve CSS Custom Variables

### ISSUE THREAD

**Issue by iahu** [webpack-contrib/css-loader#708]
**Do you want to request a *feature* or report a *bug*?**
report a *bug*

**What is the current behavior?**
CSS Custom Variables be compiled as normal css property, like the split properties compile to be a shorthand property.

**If the current behavior is a bug, please provide the steps to reproduce.**
```css
:root {
  --balloon-size-padding-top: 16px;
  --balloon-size-padding-right: 16px;
  --balloon-size-padding-bottom: 16px;
  --balloon-size-padding-left: 16px;
}
```
will be compiled to
```css
:root {padding:16px}
```

**What is the expected behavior?**
expected keep the `CSS Custom Variables properties`
```
:root{--balloon-size-padding-top:16px;--balloon-size-padding-right:16px;--balloon-size-padding-bottom:16px;--balloon-size-padding-left:16px;}
```

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**
node v8.9.1
webpack 3.8.1

**Comment by evilebottnawi** [comment]
Test for this https://github.com/webpack-contrib/css-loader/pull/709

**Comment by evilebottnawi** [comment]
Main CI passed https://travis-ci.org/webpack-contrib/css-loader/builds/373920345?utm_source=github_status&utm_medium=notification. Looks like you have other plugins for `postcss-loader` or other loader what minimize you css or plugin for css minification and he is remove this. Not related to `css-loader`. Thanks!

**Comment by iahu** [comment]
Thanks you reply.
I have trace the issue some times, and find it only happens at merging longhand properties to shorthand property. maybe we should add some case like
```css
:root {
    --box-padding-top: 10px;
    --box-padding-right: 10px;
    --box-padding-bottom: 10px;
    --box-padding-left: 10px;
}
```
In fact, I have made a [fork repository](https://github.com/iahu/css-loader/commit/41a182954fb1020ece7b970657697d5386e3a97f) to test this case, you can clone it to run test command.
