### ISSUE TITLE
[question] How to disable flattening files with use processCssUrls?

### ISSUE THREAD

**Issue by andrey-helldar** [webpack-contrib/css-loader#756]
I have the following file structure:
```
│─ resources
│  ├─ scss
│  │  └─ styles.scss
│  └─ fonts
│     └─ mercedes-benz
│        └─ DaimlerCAC
│           └─ DaimlerCAC-Regular.eot
│           └─ DaimlerCAC-Regular.svg
│           └─ DaimlerCAC-Regular.ttf
│           └─ DaimlerCAC-Regular.woff
│           └─ DaimlerCAC-Regular.woff2
```

When compiled, the destination file copies the files to the folder `public/fonts`:
```css
@font-face {
    font-family: 'Corporate A Condensed';
    src: local("Corporate A Condensed"),
    url(/fonts/DaimlerCAC-Regular.eot?b59049d589ef6a8a6908a4d616de4f32),
    url(/fonts/DaimlerCAC-Regular.eot?b59049d589ef6a8a6908a4d616de4f32) format("embedded-opentype"),
    url(/fonts/DaimlerCAC-Regular.woff2?b5b750900832b055cb8fe554b0d5d7ed) format("woff2"),
    url(/fonts/DaimlerCAC-Regular.woff?43184258c348317eab8e4b4dc2e3c2a0) format("woff"),
    url(/fonts/DaimlerCAC-Regular.ttf?858b755a54bc64c55cca3fafd5e4800e) format("truetype"),
    url(/fonts/DaimlerCAC-Regular.svg?e730a6e7de830b331d3ee6c7ade1933b) format("svg")
}
```

Given that the site uses several fonts, eventually the `fonts` folder contains about 119 files.
Tell me, how can I save the option `processCssUrls: true` to copy files while saving paths?

For example:
```css
@font-face {
    font-family: 'Corporate A Condensed';
    src: local("Corporate A Condensed"),
    url(/fonts/mercedes-benz/DaimlerCAC/DaimlerCAC-Regular.eot?b59049d589ef6a8a6908a4d616de4f32),
    url(/fonts/mercedes-benz/DaimlerCAC/DaimlerCAC-Regular.eot?b59049d589ef6a8a6908a4d616de4f32) format("embedded-opentype"),
    url(/fonts/mercedes-benz/DaimlerCAC/DaimlerCAC-Regular.woff2?b5b750900832b055cb8fe554b0d5d7ed) format("woff2"),
    url(/fonts/mercedes-benz/DaimlerCAC/DaimlerCAC-Regular.woff?43184258c348317eab8e4b4dc2e3c2a0) format("woff"),
    url(/fonts/mercedes-benz/DaimlerCAC/DaimlerCAC-Regular.ttf?858b755a54bc64c55cca3fafd5e4800e) format("truetype"),
    url(/fonts/mercedes-benz/DaimlerCAC/DaimlerCAC-Regular.svg?e730a6e7de830b331d3ee6c7ade1933b) format("svg")
}
```

?
