### ISSUE TITLE
force importing into a namespace

### ISSUE THREAD

**Issue by brewster1134** [webpack-contrib/css-loader#778]
i am looking for a way to force a module css namespace to prevent accidental "style pollution". something like...

###### foo.css
```css
.title {
  background: red;
}
```

so when i import...
```js
import './foo.css'
```

based on the css file name for example, i would get...

```css
.foo {
  .title {
    background: red;
  }
}
```

is this possible?
