### ISSUE TITLE
a way to assign the result of a required css file to :global

### ISSUE THREAD

**Issue by bdefore** [webpack-contrib/css-loader#80]
Before using css modules, I was able to import styles from `react-select` defaults using the following:

`require('react-select/dist/default.css');`

But those styles are not required by default to `:global` and since they are not being referenced anywhere explicitly they are not being included in the bundle. A workaround I've made is to duplicate the default.css and prepend all selectors with `:global(.class-name)` but it'd be nice if I could signify that I'd like this require to be loaded into :global along the lines of:

`require('global!react-select/dist/default.css');`

**Comment by sokra** [comment]
``` js
module: {
  loaders: [
    [
      {
        test: /\.css$/,
        include: path.resolve("./node_modules/react-select"),
        loader: "style-loader!css-loader"
      },
      { test: /\.css$/, loader: "style-loader!css-loader?modules" },
  ]
}
```

**Comment by dtothefp** [comment]
It seems like when creating/using a global module it would be more useful to do something like

```css
.flex,
:global .flex {
  display: flex;
}
```
but this throws an error in the css-loader. It seems that in the example above if you wanted to use something out of the `react-select` module locally, and then something globally, you would get duplicated code.

**Comment by sokra** [comment]
``` css
.flex,
:global(.flex) {
  display: flex;
}
```

**Comment by dtothefp** [comment]
@sokra thanks for the tip. I'm a little confused because when looking at this example they are able to use `:global` without the parenthesis, which I was assuming was "sugar".

https://github.com/css-modules/webpack-demo/blob/master/src/components/2-GlobalSelectors/GlobalSelectors.css

Confusing why that works for the scenario for only one class name, but not when two class names are associated with a given css block:

*Works*
```css
.flex-row,
:global(.flex-row) {
  flex-direction: row;
}

:global .flex-column {
  flex-direction: column;
}
```


*Doesn't Work*
```css
.flex-row,
:global .flex-row {
  flex-direction: row;
}

:global .flex-column {
  flex-direction: column;
}
```
