### ISSUE TITLE
Support `image-set` notation without `url` notation

### ISSUE THREAD

**Issue by evilebottnawi** [webpack-contrib/css-loader#833]
* Operating System: no matter
* Node Version: no matter
* NPM Version: no matter
* webpack Version: no matter
* css-loader Version: no matter

### Feature Proposal

```css
.class {
  background-image: image-set("img1x.png" 1x, "img2x.png" 2x);
}
```

### Feature Use Case

Use `require` on this images.
