### ISSUE TITLE
Resolving import/compose css paths in node_module with version 2.0.0

### ISSUE THREAD

**Issue by mbulfair** [webpack-contrib/css-loader#861]
* Operating System: OS X
* Node Version: 10.13.0
* NPM Version: 6.4.1
* webpack Version: 4.27.1
* css-loader Version: 2.0.0

### Actual Behavior

Importing with css compose and import to a node module. In version 1.0.1 the `~` was not needed. In 2.0.0 it is. While in my local project I can change any references to this with no issue. However in the node_module/package/file.css if it doesn't have that same `~` then webpack/css loader can't resolve the path. 

### Code
Below works with 1x and partially with 2x,

also in the test of css, I am excluding a series of local node_modules, internal only packages. This may be some of the issue. 

```js
{
   loader: "css-loader",
              options: {
                modules: true,
                localIdentName: "[name]__[local]-[hash:base64:5]",
                url: false,
                importLoaders: 1
              }
            },
```
### How Do We Reproduce?

Local File:

```css
@value color-grey from "~@localpackage/styles/color.css";

.copyright {
  color: color-grey;
  composes: type-heading from "~@localpackage/theme/styles/typography.css";
  margin: 0;
  padding: 0;
}
```

Node Module

```css

.type-heading {
  color: red
  composes: type-heading2 from "@localpackage/theme/styles/typography.css";
  margin: 0;
  padding: 0;
}

```
Error in resolving ☝️ with local webpack build

**Comment by evilebottnawi** [comment]
@mbulfair fixing this error introduce problems in resolving algorithm and can introduce more bugs in future (other developers can forget about using `~` for modules and it is introduce more error). i need more time to investigate how better solve this problem. As workaround we can create simple loader and add this in documentation for this package.

**Comment by evilebottnawi** [comment]
Why it is not easy. Let's see on:
```css
a {
  background: url(@images/image.png);
}
```
Note: `@` is valid symbol in any filesystem (known for me).

Now we resolve this as `./@images/image.png`, but if we return resolving without `~` this can be resolving as:
- ./@image/image.png
- node_modules/@images/image.png

What is right resolving? Nobody knows, so we introduced `~` characters. it allows us to distinguish module requesting (from node_modules) and usual require.

In `JS` this problem doesn't exists because we have RFC on `require` where described what `require('@images/image.png')` mean load `image.png` from `@image` repo in `node_modules`. There is no such thing in css.

Why we interpreted `url('image.png')`, `url('something/image.png')` and `url(@something/image.png)` as relative request (i.e. `./image.png`, `./something/image.png` and `./@something/image.png`)? For better compatibility with existing libraries and frameworks.

Feel free to feedback.
