### ISSUE TITLE
`undefined` URL.

### ISSUE THREAD

**Issue by Lattyware** [webpack-contrib/css-loader#864]
After upgrading to 2.0.0 from 1.0.1, I am getting `url(undefined)` in my output CSS where I previously got a valid URL.

This seems to happen when the URL is referenced multiple times - after the first reference `undefined` is output.

* Operating System: Arch Linux
* Node Version: 11.3.0
* NPM Version: 6.4.1
* webpack Version: 4.27.1
* css-loader Version: 2.0.0

### Expected Behavior

The URL should be output.

### Actual Behavior

`undefined` is output instead of the URL.

### Code

```css
@import "./test2";

.test1 {
    background: url(../../assets/test.png);
}
```

```css
.test2 {
    background: url(../../assets/test.png) repeat;
}
```

Produces:

```css
.test2{background:url(d41d8cd98f00b204e9800998ecf8427e.png) repeat}.test1{background:url(undefined)}
```

### How Do We Reproduce?

See [the attached project](https://github.com/webpack-contrib/css-loader/files/2660638/css-loader-bug.zip), which works with `css-loader@1.0.1` but fails with `css-loader@2.0.0`.
