### ISSUE TITLE
Query string gets removed in url() call to a local file

### ISSUE THREAD

**Issue by szimek** [webpack-contrib/css-loader#889]
* Operating System: macOS 10.14.3
* Node Version: 11.7.0
* NPM Version: 6.5.0
* webpack Version: 4.29.0
* css-loader Version: 2.1.0
* style-loader Version: 0.23.1

### Expected Behavior

When loading images in CSS using `url()` with a query string, I'd expect this query string to be still present in the generated CSS. E.g. 
```css
{
  background: url(./icon.png?format=auto);
}
``` 
should generate
```css
{
  background: url(ca44b2d46d84acdf38fe0d3a59358c4c.png?format=auto);
}
``` 

### Actual Behavior

```css
{
  background: url(./icon.png?format=auto);
}
``` 
generates
```css
{
  background: url(ca44b2d46d84acdf38fe0d3a59358c4c.png);
}
``` 

### Code

```js
  // webpack.config.js
  module: {
    rules: [
      {
        test: /\.css$/,
        use: [
          'style-loader',
          'css-loader'
        ]
      },
      {
        test: /\.(png|svg|jpg|gif)$/,
        use: [
          'file-loader'
        ]
      }
    ]
  }
```

### How Do We Reproduce?

Add a query string to any local path in `url()` call. I can prepare a repo if necessary.
