### ISSUE TITLE
not correct import with modules

### ISSUE THREAD

**Issue by isum** [webpack-contrib/css-loader#916]
* Operating System: linux
* Node Version: v11.12.0
* NPM Version: 6.9.0
* webpack Version: 4.29.6
* sass-loader Version: 7.1.0

This issue is a continuation of https://github.com/webpack-contrib/sass-loader/issues/675

### Expected behavior

We have css-modules in webpack.config.js
```js
{loader: 'css-loader', options: {modules: true, localIdentName: '[local]-sufx'}}
```

index.scss
```scss
@import "index.css";
@import "another.scss";
.im-from-scss {
  bottom: 20px;
}
```

index.css
```css
.im-missing-from-css{
  color: blue;
}
```

another.scss
```scss
.im-from-another-scss {
  left: 40px;
} 
```

in index.js we import the index.scss
```js
import scss from './index.scss';
```

the expected value of `scss` should be
```js
{
im-missing-from-css: "im-missing-from-css-sufx",
im-from-another-scss: "im-from-another-scss-sufx",
im-from-scss: "im-from-scss-sufx"
}
```

### Actual behavior

the value of `scss` is
```js
{
im-from-another-scss: "im-from-another-scss-sufx",
im-from-scss: "im-from-scss-sufx"
}
```

the css file is not included in the dictionary.

### How to reproduce

source code: 
[bug-repo.tar.gz](https://github.com/webpack-contrib/css-loader/files/3050194/bug-repo.tar.gz)

`npm run build`

load build/index.html and see console output

**Comment by evilebottnawi** [comment]
Thanks for issue

**Comment by jquense** [comment]
does it work if the paths are relative `./index.css`, etc? I've not noticed this myself, but i tend to make them unambigious

**Comment by evilebottnawi** [comment]
@jquense hm, using `./index.css` solve problem? I think it is bug

**Comment by evilebottnawi** [comment]
After investigation i find it is not bug. Why?
1. Sass don't touch all `@import` with `css` extension, so after sass-loader you will get:
```
@import "index.css";
.im-from-another-scss {
      left: 40px;
}
    
.im-from-scss {
      bottom: 20px;
}
```
2. css-loader handle `@import` as css import

It is edge case, solution - rename `index.css` to `index_in_sass.css` (any name) and remove `css` extension from '@import':
```scss
@import "index_in_sass";
@import "another.scss";
.im-from-scss {
  bottom: 20px;
}
```

Unfortunately we can’t do anything here because this is how sass works.
