### ISSUE TITLE
filter: saturate() not allowed in plain css

### ISSUE THREAD

**Issue by Jamesking56** [webpack-contrib/css-loader#924]
* Operating System: Ubuntu 18.04 LTS
* Node Version: v8.16.0
* NPM Version: 6.4.1
* webpack Version: ^4.27.1
* css-loader Version: ^1.0.1

### Expected Behavior

Allow `saturate()` in `filter` in CSS

### Actual Behavior

Errors: `This function isn't allowed in plain CSS.`

### Code

Not sure, using `laravel-mix`.

### How Do We Reproduce?

Add the following in CSS:

```css
#id {
  filter:hue-rotate(-20deg) contrast(.9) saturate(.85) brightness(1.2)
}
```
