### ISSUE TITLE
Support @value in url and @import

### ISSUE THREAD

**Issue by evilebottnawi** [webpack-contrib/css-loader#953]
- Operating System: linux
- Node Version: 10
- NPM Version: 6
- webpack Version: 4
- css-loader Version: 2

### Feature Proposal

```css
@value v-url: url('./test.img')

a {
  background: v-url;
}
```

Same for `@import`

### Feature Use Case

Above
