### ISSUE TITLE
ICSS: Importing a composed class name produces wrong output

### ISSUE THREAD

**Issue by joepie91** [webpack-contrib/css-loader#997]
- Operating System: Linux
- Node Version: v10.17.0
- NPM Version: n/a, Yarn 1.15.2
- webpack Version: 4.41.2
- css-loader Version: 3.2.0

### Expected Behavior

`css-loader` should produce correct output:

```css
.outer-box__outerBox--1rUd7j4- .inner-box__innerBox--19HrVC2M.shared__box--3DFGfIs1 {
	background-color: lime;
}
```

![Selection_407](https://user-images.githubusercontent.com/1663259/69487032-98fccc00-0e53-11ea-8ad2-703118887ded.png)

### Actual Behavior

`css-loader` produces incorrect output:

```css
.outer-box__outerBox--1rUd7j4- .inner-box__innerBox--19HrVC2M shared__box--3DFGfIs1 {
	background-color: lime;
}
```

![Selection_406](https://user-images.githubusercontent.com/1663259/69487037-aa45d880-0e53-11ea-8b2e-9b42262e529e.png)

### Code

See below.

### How Do We Reproduce?

Full repro case here: https://git.cryto.net/joepie91/icss-loader-test

Run `yarn webpack` to produce output with Webpack + css-loader (incorrect output), run `yarn browserify-extract` to produce output with Browserify + icssify (correct output).

Both output to the same files, so you can switch between them. Open `test/index.html` in a browser to see the result.

The bug is caused by the `import` handling using the JS/HTML-formatted (space-delimited) export, rather than a CSS-formatted (dot-delimited) export.

This means that when using a composed identifier (which consists of two space-delimited class names) as an imported identifier, the resulting selector rule will be broken (see code snippets above).

This can be fixed by [replacing spaces with dots](https://git.cryto.net/joepie91/icssify/src/c519e107e3e2618a844a5a840d306f6c7ce0c98b/src/postcss/postprocess.js#L39) in the case of ICSS imports.

**Comment by evilebottnawi** [comment]
Thanks for issue i will look on this in near future

**Comment by yakato** [comment]
I have the same. After update all new `react-scripts` dependencies, also `css-loader` updated. With the latest version my all code based on  CSS-Modules `composes` is broken.

**Comment by evilebottnawi** [comment]
@yakato please create reproducible test repo

**Comment by apexskier** [comment]
Might be related to https://github.com/webpack-contrib/css-loader/issues/561, which has a minimal reproduction.

**Comment by joepie91** [comment]
@apexskier That's a different issue, about imports not working *at all*. That has since been fixed, as far as I can tell.

The remaining issue is that specifically *composed* class names are not handled correctly, for which I've provided a reproduction in the initial report above.

**Comment by OHUSAR** [comment]
Hello.

We are also experiencing similar issue to this. In our case its an issue with using `composes` with dynamically imported `css chunks`.

I have created a minimal reproduction:

https://github.com/OHUSAR/css-modules-chunk-specificity-bug

@evilebottnawi is this an issue, you will be considering to look into, or should we use different way of solving our problems? Thank you for your answer!

The precise definition of the problem (pasted from README.md):

Let's consider having these source files:

* a.module.css
    ```
    .test {
        background-color: red;
    }
    ```

* b.module.css
    ```
    .test2 {
        composes: test from "./a.module.css";
        background-color: blue;
    }
    ```
* c.module.css
    ```
    .test3 {
        composes: test from "./a.module.css";
        background-color: green;
    }
    ```

<br/>
The output of these files would be:

* a.module.css
    ```
    .test {
        background-color: red;
    }
    ```

* b.module.css
    ```
    .test {
        background-color: red;
    }

    .test2 {
        background-color: blue;
    }
    ```
* c.module.css
    ```
    .test {
        background-color: red;
    }

    .test3 {
        background-color: green;
    }
    ```
<br/>
Now let's consider that our code dynamically imports chunk with output of a.module.css and c.module.css and than later imports chunk with b.module.css output.

The current applied css would be:

```
    .test {
        background-color: red;
    }

    .test {
        background-color: red;
    }

    .test3 {
        background-color: green;
    }

    .test {
        background-color: red;
    }

    .test2 {
        background-color: blue;
    }

```

When considering element using classnames from c.module.css,
```
    <div class="test_localname test3_localname" />
```
the applied background color of the C element would be red instad of green. The reason for this is that the class `.test` is included later in the css hierarchy and therefore is used for element style.

**Comment by evilebottnawi** [comment]
@OHUSAR It should be fixed, can you create reproducible test repo, thanks

**Comment by OHUSAR** [comment]
Ok. I will create a separate issue, with full description and all thats needed.

**Comment by evilebottnawi** [comment]
@OHUSAR You can put a problem here if it will be other problem I will create issue from comment

**Comment by OHUSAR** [comment]
- Operating System: Ubuntu 16.04.5 LTS
- Node Version: v10.19.0
- NPM Version: 6.13.4
- webpack Version: 4.42.1
- css-loader Version: 3.4.1 (used in latest CRA https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/package.json)

### Expected Behavior

After dynamically importing component, which composes css class, that an already present component also composes, the existing component should preserve its styles.

![Screenshot from 2020-04-06 11 22 27](https://user-images.githubusercontent.com/14111857/78543876-98a91000-77f9-11ea-9458-e94a9d7a6619.png)




### Actual Behavior

After dynamically importing component `B`, components `C` styles get overriden. 

![Screenshot from 2020-04-06 11 22 52](https://user-images.githubusercontent.com/14111857/78544066-e160c900-77f9-11ea-805c-73f72cc50b30.png)



### Code

```
// index.module.css

.test {
    background-color: red;
    padding: 30px;
}
```
```
// b.module.css

.test2 {
    composes: test from '../index.module.css';
    background-color: blue;
}
```

```
// c.moodule.css

.test3 {
    composes: test from '../index.module.css';
    background-color: green;
}
```

**Result**:

```html
<head>
    <link rel="stylesheet" type="text/css" href="chunk-2.css">
    <script charset="utf-8" src="2.main.js"></script>
    <link rel="stylesheet" type="text/css" href="chunk-1.css">
    <script charset="utf-8" src="1.main.js"></script>
</head>
```

```css
// chunk-2.css

._2D6NmF3oNXamuyZ2z-z6-2 {
  background-color: red;
  padding: 30px;
}

._2vSpwQvfEWT-h3qiyUMFPO {
  background-color: green;
}
```

```css
// chunk-1.css

._2D6NmF3oNXamuyZ2z-z6-2 {
  background-color: red;
  padding: 30px;
}

._3IkLTxcAE-k8TWXxjYQrik {
  background-color: blue;
}
```

**Webpack config:**

```js
// webpack.config.js
...
    module: {
        rules: [
            {
                test: /\.module\.css$/i,
                use: [
                    { loader: MiniCssExtractPlugin.loader },
                    {
                        loader: 'css-loader',
                        options: {
                            modules: true,
                            importLoaders: 1,
                        },
                    },
                ],
            },
        ],
    },
...
```

### How Do We Reproduce?

For reproduction, see this minimal repo:
https://github.com/OHUSAR/css-modules-chunk-specificity-bug

**Comment by evilebottnawi** [comment]
@OHUSAR Thanks, I will look at that in near future

**Comment by OHUSAR** [comment]
@evilebottnawi any updates on this please? thank you

**Comment by evilebottnawi** [comment]
@OHUSAR Looks like a limitation, I think it can't be fixed without other problems

**Comment by evilebottnawi** [comment]
@OHUSAR Problem on `mini-css-extract-plugin` side, https://github.com/webpack-contrib/mini-css-extract-plugin/issues/555

**Comment by evilebottnawi** [comment]
Sorry for delay, WIP on the issue, maybe we need improve our architecture, also it is allow to validate existing names and throw an error on the build step

**Comment by evilebottnawi** [comment]
Here big problem :disappointed: @joepie91 You example is broken too. 

Example:

**inner-box.css**

```css
@value shadow: 10px 5px 5px red;

.innerBox {
	composes: box from "./shared.css";
	width: 64px;
	height: 64px;
	background-color: red;
}
```

**outer-box.css**

```css
:import("./inner-box.css") {
	importedInnerBox: innerBox;
}

@value shadow from './inner-box.css';

.outerBox {
	composes: box from "./shared.css";
	width: 100px;
	height: 100px;
	background-color: blue;
	box-shadow: shadow;
}

.outerBox .importedInnerBox {
	background-color: lime;
}
```

And look at bundle:
```
"shadow":"10px.5px.5px.red"
```

We replace spaces on `.`, but it is invalid.

Don't know how we can solve it, because we don't know this values on the build step and don't know context, what we know? Only value.
